#include "global.h"

const u8 *const gBattleStringsTable[611] =
{
    [0] = COMPOUND_STRING("{B_TRAINER1_LOSE_TEXT}"),    // 0x8df5570
    [1] = COMPOUND_STRING("{B_BUFF1}获得了{B_BUFF2}\n{B_BUFF3} 点经验值！\p"),    // 0x8df559e
    [2] = COMPOUND_STRING("{B_BUFF1}升到了\nLV. {B_BUFF2}！{WAIT_SE}\p"),    // 0x8df5608
    [3] = COMPOUND_STRING("{B_BUFF1}学会了\n{B_BUFF2}！{WAIT_SE}\p"),    // 0x8df561e
    [4] = COMPOUND_STRING("{B_BUFF1}正在尝试\n学习{B_BUFF2}。\p"),    // 0x8df5630
    [5] = COMPOUND_STRING("但是, {B_BUFF1}已经不能\n习得更多的招式了。\p"),    // 0x8df564b
    [6] = COMPOUND_STRING("忘记一个招式\n来学习{B_BUFF2}?"),    // 0x8df5676
    [7] = COMPOUND_STRING("{B_BUFF1}忘记了\n{B_BUFF2}。\p"),    // 0x8df5699
    [8] = COMPOUND_STRING("{PAUSE 32}放弃习得\n{B_BUFF2}?"),    // 0x8df56a8  
    [9] = COMPOUND_STRING("{B_BUFF1}没有学习\n{B_BUFF2}。\p"),    // 0x8df56bd
    [10] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}学会了\n{B_BUFF1}！"),    // 0x8df7595
    [11] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}的\n攻击没能命中！"),    // 0x8df56e5
    [12] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}\n保护了自身！"),    // 0x8df56f9
    [13] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}的能力\n不能再提升了！"),    // 0x8df6f5b
    [14] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}凭借{B_DEF_ABILITY}\n避免了伤害！"),    // 0x8df570e
    [15] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}\n没有受到影响⋯"),    // 0x8df5764
    [16] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}\n倒下了！\p"),    // 0x8df577a
    [17] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}\n倒下了！\p"),    // 0x8df5787
    [18] = COMPOUND_STRING("{B_PLAYER_NAME}收到了{B_BUFF1}元和{B_BUFF2} 点BP\n作为奖励！\p"),    // 0x8df5794
    [19] = COMPOUND_STRING("{B_PLAYER_NAME}已经没有\n可用的宝可梦了！\p"),    // 0x8df585f
    [20] = COMPOUND_STRING("{B_PLAYER_NAME}慌乱中丢失了{B_BUFF1} 元⋯\p⋯ ⋯ ⋯ ⋯\p{B_PLAYER_NAME} 眼前一片黑！{PAUSE_UNTIL_PRESS}"),    // 0x8df587d
    [21] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX} 用{B_SCR_ACTIVE_ABILITY}\n 阻止了逃跑！\p"),    // 0x8df58b0
    [22] = COMPOUND_STRING("命中了{B_BUFF1}次！"),    // 0x8df58ed
    [23] = COMPOUND_STRING("{B_EFF_NAME_WITH_PREFIX}\n开始睡着了！"),    // 0x8df58fd
    [24] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}的 {B_SCR_ACTIVE_ABILITY}\n让 {B_EFF_NAME_WITH_PREFIX} 睡着了！"),    // 0x8df590d
    [25] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}\n已经睡着了！"),    // 0x8df5924
    [26] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}\n已经睡着了！"),    // 0x8df593a
    [27] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}\n没有受到影响！"),    // 0x8df5950
    [28] = COMPOUND_STRING("{B_EFF_NAME_WITH_PREFIX}\n中毒了！"),    // 0x8df5964
    [29] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX} 的{B_BUFF1}\n使 {B_EFF_NAME_WITH_PREFIX}中毒了！"),    // 0x8df5975
    [30] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}因中毒\n受到了伤害！"),    // 0x8df5991
    [31] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}\n中毒了。"),    // 0x8df59a7
    [32] = COMPOUND_STRING("{B_EFF_NAME_WITH_PREFIX}中了剧毒！"),    // 0x8df59bf
    [33] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}\n被吸取了能量！"),    // 0x8df59d5
    [34] = COMPOUND_STRING("{B_EFF_NAME_WITH_PREFIX}烧伤了！"),    // 0x8df59f0
    [35] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}的{B_SCR_ACTIVE_ABILITY}\n使{B_EFF_NAME_WITH_PREFIX}烧伤了！"),    // 0x8df59ff
    [36] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}\n因烧伤受到了伤害！"),    // 0x8df5a12
    [37] = COMPOUND_STRING("{B_EFF_NAME_WITH_PREFIX}\n被冰冻！"),    // 0x8df5a41
    [38] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}的{B_SCR_ACTIVE_ABILITY}\n使{B_EFF_NAME_WITH_PREFIX}被冰冻了！"),    // 0x8df5a56
    [39] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}被\n冰冻了！"),    // 0x8df5a6e
    [40] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}\n解除了冰冻！"),    // 0x8df5a82
    [41] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}\n解除了冰冻！"),    // 0x8df5a94
    [42] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}因{B_CURRENT_MOVE}\n解除了冰冻！"),    // 0x8df5aa6
    [43] = COMPOUND_STRING("{B_EFF_NAME_WITH_PREFIX}麻痹了！\n可能无法行动！"),    // 0x8df5abe
    [44] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}的{B_SCR_ACTIVE_ABILITY}\n使{B_EFF_NAME_WITH_PREFIX}麻痹了！\l可能无法行动！"),    // 0x8df5ae9
    [45] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}麻痹了！\n无法行动！"),    // 0x8df5b19
    [46] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}\n已经麻痹了！"),    // 0x8df5b39
    [47] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}的身体\n不再麻痹了！"),    // 0x8df5b52
    [48] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}的梦\n被吃了！"),    // 0x8df5b6e
    [49] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}的{B_BUFF1}\n已经无法上升了！"),    // 0x8df5b84
    [50] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}的{B_BUFF1}\n已经无法下降了！"),    // 0x8df5b9d
    [51] = COMPOUND_STRING("我方的{B_BUFF1}\n失去了作用！"),    // 0x8df5bb5
    [52] = COMPOUND_STRING("对手的{B_BUFF1}\n失去了作用！"),    // 0x8df5bd5
    [53] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}\n混乱了！"),    // 0x8df5bf3
    [54] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}\n解除了混乱！"),    // 0x8df5c03
    [55] = COMPOUND_STRING("{B_EFF_NAME_WITH_PREFIX}\n开始混乱了！"),    // 0x8df5c20
    [56] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}\n已经混乱了！"),    // 0x8df5c34
    [57] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}\n被迷倒了！"),    // 0x8df5c4c
    [58] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}因\n{B_SCR_ACTIVE_NAME_WITH_PREFIX}迷倒了！"),    // 0x8df5c5d
    [59] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}因\n迷倒无法行动！"),    // 0x8df5c74
    [60] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}被\n吹飞了！"),    // 0x8df5c8f
    [61] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}变成了\n{B_BUFF1}系！"),    // 0x8df5ca2
    [62] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}动弹不得！"),    // 0x8df5cc3
    [63] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}\n恢复了健康！"),    // 0x8df5cd0
    [64] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}的\nHP满了！"),    // 0x8df5ce4
    [65] = COMPOUND_STRING("{B_ATK_PREFIX2}的{B_CURRENT_MOVE}\n提升了特防！"),    // 0x8df5cf5
    [66] = COMPOUND_STRING("{B_ATK_PREFIX2}的{B_CURRENT_MOVE}\n稍微提升了特防！"),    // 0x8df5d2e
    [67] = COMPOUND_STRING("{B_ATK_PREFIX2}的一方\n被神秘的面纱包裹了！"),    // 0x8df5d67
    [68] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}的一方被\n神秘护身保护了！"),    // 0x8df5d88
    [69] = COMPOUND_STRING("{B_ATK_PREFIX3}的一方\n不再受神秘护身保护了！"),    // 0x8df5dae
    [70] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}\n睡着了！"),    // 0x8df5dde
    [71] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}睡着了\n并且恢复了体力！"),    // 0x8df5df0
    [72] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}\n使出了旋风！"),    // 0x8df5e0d
    [73] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}\n吸收了阳光！"),    // 0x8df5e28
    [74] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}的头\n往后缩了下！"),    // 0x8df5e3d
    [75] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}正在发光！"),    // 0x8df5e52
    [76] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}\n飞向了高空！"),    // 0x8df5e61
    [77] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}挖向了地下！"),    // 0x8df5e72
    [78] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}因\n{B_ATK_NAME_WITH_PREFIX}的绑紧被绑住了！"),    // 0x8df5ea2//不确认
    [79] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}被困于\n漩涡中！"),    // 0x8df5ec0
    [80] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}被\n{B_ATK_NAME_WITH_PREFIX}捆绑了！"),    // 0x8df5efb//不确认
    [81] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}的壳夹着\n{B_DEF_NAME_WITH_PREFIX}！"),    // 0x8df5f11
    [82] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}因\n{B_BUFF1}受到伤害！"),    // 0x8df5f20
    [83] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}不受\n{B_BUFF1}的影响了！"),    // 0x8df5f32
    [84] = COMPOUND_STRING("强力的冲击使{B_ATK_NAME_WITH_PREFIX}\n摔倒了！"),    // 0x8df5f48
    [85] = COMPOUND_STRING("{B_ATK_PREFIX2}\n被白雾笼罩了！"),    // 0x8df5f63
    [86] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}\n被白雾保护了！"),    // 0x8df5f7f
    [87] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}\n变得兴奋了！"),    // 0x8df5f98
    [88] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}\n受到了反馈伤害！"),    // 0x8df5fae
    [89] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}\n保护了自己！"),    // 0x8df5fc5
    [90] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}因\n沙暴受到了伤害！"),    // 0x8df5fda
    [91] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}因\n冰雹受到了伤害！"),    // 0x8df5ffb
    [92] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}被种了种子！"),    // 0x8df6023
    [93] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}\n回避了攻击！"),    // 0x8df6032
    [94] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}的HP\n因寄生种子减少了！"),    // 0x8df6048
    [95] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}熟睡了。"),    // 0x8df606d
    [96] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}醒来了！"),    // 0x8df6080
    [97] = COMPOUND_STRING("但是，{B_SCR_ACTIVE_NAME_WITH_PREFIX}的吵闹\n让它保持了清醒！"),    // 0x8df608c
    [98] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}\n在吵闹中醒来！"),    // 0x8df60ab//不确认
    [99] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}\n引起了吵闹！"),    // 0x8df60c5
    [100] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}\n在制造吵闹！"),    // 0x8df60da
    [101] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}平静了下来。"),    // 0x8df60f2
    [102] = COMPOUND_STRING("但是，{B_DEF_NAME_WITH_PREFIX}无法在\n吵闹中睡眠！"),    // 0x8df6102
    [103] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}储存了\n{B_BUFF1}！"),    // 0x8df6123
    [104] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}\n不能再储存了！"),    // 0x8df6135
    [105] = COMPOUND_STRING("但是，{B_DEF_NAME_WITH_PREFIX}在\n吵闹中不会睡着！"),    // 0x8df6152
    [106] = COMPOUND_STRING("但是，吵闹使得\n{B_DEF_NAME_WITH_PREFIX}保持清醒！"),    // 0x8df6173
    [107] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}在清醒中\n使用它的{B_DEF_ABILITY}！"),    // 0x8df6191
    [108] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}\n积蓄了能量！"),    // 0x8df61af
    [109] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}\n释放了能量！"),    // 0x8df61c5
    [110] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}由于\n疲劳变得混乱！"),    // 0x8df61da
    [111] = COMPOUND_STRING("{B_PLAYER_NAME}捡到了\n{B_BUFF1}元！\p"),    // 0x8df61fd
    [112] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}\n没受到影响！"),    // 0x8df6210
    [113] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}变身为\n{B_BUFF1}！"),    // 0x8df6222
    [114] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}\n制造了一个替身！"),    // 0x8df623a
    [115] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}已经\n有一个替身了！"),    // 0x8df6250
    [116] = COMPOUND_STRING("替身为\n{B_DEF_NAME_WITH_PREFIX}承受了伤害！\p"),    // 0x8df626d
    [117] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}的\n替身消失了！\p"),    // 0x8df6291
    [118] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}\n必须恢复能量！"),    // 0x8df62a9
    [119] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}\n已经愤怒了！"),    // 0x8df62bb
    [120] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}的{B_BUFF1}\n无法起作用！"),    // 0x8df62d2
    [121] = COMPOUND_STRING("{B_ACTIVE_NAME_WITH_PREFIX}的{B_CURRENT_MOVE}\n无法起作用！\p"),    // 0x8df6a3b
    [122] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}\n不再起作用！"),    // 0x8df62e8
    [123] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}\n中了再来一次！"),    // 0x8df6300
    [124] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}对\n再来一次免疫！"),    // 0x8df6312
    [125] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}\n瞄准了{B_DEF_NAME_WITH_PREFIX}！"),    // 0x8df6325
    [126] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}对\n{B_BUFF1}做素描！"),    // 0x8df6338
    [127] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}试图\n与对手同归于尽！"),    // 0x8df6348
    [128] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}与\n{B_ATK_NAME_WITH_PREFIX}同归于尽！"),    // 0x8df636e
    [129] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}的{B_BUFF1}减少了\n{B_BUFF2}点！"),    // 0x8df6382
    [130] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}偷窃了\n{B_DEF_NAME_WITH_PREFIX}的{B_LAST_ITEM}！"),    // 0x8df6399
    [131] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}暂时\n不能逃跑！"),    // 0x8df63ab
    [132] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}\n堕入了恶梦之中！"),    // 0x8df63c0
    [133] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}\n被困于恶梦之中！"),    // 0x8df63da
    [134] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}减半了自身的HP，\n并给{B_DEF_NAME_WITH_PREFIX}施加了诅咒！"),    // 0x8df63f7
    [135] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}受到了\n诅咒造成的伤害！"),    // 0x8df6421
    [136] = COMPOUND_STRING("铁菱已经遍布\n对手的周围！"),    // 0x8df643f
    [137] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}受到\n铁菱的伤害！"),    // 0x8df6475
    [138] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}鉴别了\n{B_DEF_NAME_WITH_PREFIX}！"),    // 0x8df648b
    [139] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}的灭亡回合\n只剩下{B_BUFF1}回合！"),    // 0x8df649d
    [140] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}挺住了！"),    // 0x8df64bb
    [141] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}忍耐了攻击！"),    // 0x8df64cd
    [142] = COMPOUND_STRING("震级{B_BUFF1}！"),    // 0x8df64e1
    [143] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}的HP减少了，\n并且攻击上升至最高！"),    // 0x8df64ef
    [144] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}复制了\n{B_DEF_NAME_WITH_PREFIX}的能力等级！"),    // 0x8df6517
    [145] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}解脱了\n{B_DEF_NAME_WITH_PREFIX}的{B_BUFF1}！"),    // 0x8df6534
    [146] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}\n摆脱了寄生种子！"),    // 0x8df654c
    [147] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}\n清除了铁菱！"),    // 0x8df6560
    [148] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}从对战中\n逃脱了！"),    // 0x8df6575
    [149] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}\n预知了攻击！"),    // 0x8df658a
    [150] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}挡下了\n{B_BUFF1}的攻击！"),    // 0x8df65a0
    [151] = COMPOUND_STRING("{B_BUFF1}的攻击！"),    // 0x8df65d3
    [152] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}将\n焦点集中在自身！"),    // 0x8df65e0
    [153] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}\n开始积蓄能量！"),    // 0x8df6603
    [154] = COMPOUND_STRING("自然能力变成了\n{B_CURRENT_MOVE}！"),    // 0x8df661c
    [155] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}的状态\n恢复了正常！"),    // 0x8df6639
    [156] = COMPOUND_STRING("{B_ACTIVE_NAME_WITH_PREFIX} 没有剩余招式了！\p"),    // 0x8df6a24
    [157] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}\n受到了无理取闹的影响！"),    // 0x8df6659
    [158] = COMPOUND_STRING("{B_ACTIVE_NAME_WITH_PREFIX}由于无理取闹\n不能使用同一招式！\p"),    // 0x8df6a51
    [159] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}\n集中了力量！"),    // 0x8df6676
    [160] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}\n受到了挑衅！"),    // 0x8df6692
    [161] = COMPOUND_STRING("由于挑衅，{B_ACTIVE_NAME_WITH_PREFIX}\n无法使用{B_CURRENT_MOVE}\p"),    // 0x8df6a8a
    [162] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}\n准备帮助{B_DEF_NAME_WITH_PREFIX}！"),    // 0x8df66a9
    [163] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}与对手\n交换了携带道具！"),    // 0x8df66c1
    [164] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}模仿了\n{B_DEF_NAME_WITH_PREFIX}的{B_DEF_ABILITY}！"),    // 0x8df6726
    [165] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}许了一个愿！"),    // 0x8df6739
    [166] = COMPOUND_STRING("{B_BUFF1}的许愿\n实现了！"),    // 0x8df6749
    [167] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}扎下了根！"),    // 0x8df675e
    [168] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}\n汲取了根茎的养分！"),    // 0x8df6774
    [169] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}把自身\n用根茎紧紧固定住了！"),    // 0x8df679a
    [170] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}使得\n{B_DEF_NAME_WITH_PREFIX}昏昏欲睡！"),    // 0x8df67bd
    [171] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}打破了\n{B_DEF_NAME_WITH_PREFIX}的{B_LAST_ITEM}！"),    // 0x8df67d0
    [172] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}\n与对手互换了特性！"),    // 0x8df67e8
    [173] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}\n封印了对手的招式！"),    // 0x8df6810
    [174] = COMPOUND_STRING("{B_ACTIVE_NAME_WITH_PREFIX}无法使用\n被封印的{B_CURRENT_MOVE}！\p"),    // 0x8df6aac
    [175] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}\n让对手背负怨恨！"),    // 0x8df6832
    [176] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}的{B_BUFF1}\n失去了所有的PP！"),    // 0x8df685a
    [177] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}将\n自身笼罩在{B_CURRENT_MOVE}中！"),    // 0x8df6885
    [178] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}的{B_CURRENT_MOVE}\n因为魔法反射被反弹了！"),    // 0x8df689f
    [179] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}等待目标\n的招式！"),    // 0x8df68c7
    [180] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}抢夺了\n{B_SCR_ACTIVE_NAME_WITH_PREFIX}的招式！"),    // 0x8df68ed
    [181] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}的{B_SCR_ACTIVE_ABILITY}\n使天空下起了雨！"),    // 0x8df6aee
    [182] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}的{B_SCR_ACTIVE_ABILITY}\n提升了速度！"),    // 0x8df6b04
    [183] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}受到了\n{B_DEF_ABILITY}的保护！"),    // 0x8df6b1e
    [184] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}的{B_DEF_ABILITY}\n防止了{B_ATK_NAME_WITH_PREFIX}\l使用 {B_CURRENT_MOVE}！"),    // 0x8df6b36
    [185] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}因{B_DEF_ABILITY}\n恢复了HP！"),    // 0x8df6b59
    [186] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}的{B_DEF_ABILITY}\n使它变成{B_BUFF1}！"),    // 0x8df6b8f
    [187] = COMPOUND_STRING("{B_EFF_NAME_WITH_PREFIX}的{B_DEF_ABILITY}\n抵御了麻痹！"),    // 0x8df6bac
    [188] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}的{B_DEF_ABILITY}\n抵御了迷人！"),    // 0x8df6bc8
    [189] = COMPOUND_STRING("{B_EFF_NAME_WITH_PREFIX}的{B_DEF_ABILITY}\n抵御了中毒！"),    // 0x8df6be2
    [190] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}的{B_DEF_ABILITY}\n抵御了混乱！"),    // 0x8df6bfe
    [191] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}的{B_DEF_ABILITY}\n提升了炎系招式的威力！"),    // 0x8df6c1a
    [192] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}因\n{B_DEF_ABILITY}固定住了自身！"),    // 0x8df6c39
    [193] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}的{B_SCR_ACTIVE_ABILITY}\n降低了{B_DEF_NAME_WITH_PREFIX}的攻击！"),    // 0x8df6c54
    [194] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}的{B_SCR_ACTIVE_ABILITY}\n防止了能力等级下降！"),    // 0x8df6c6e
    [195] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}\n被{B_DEF_NAME_WITH_PREFIX}的{B_BUFF1}所伤！\p"),    // 0x8df6c8a
    [196] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX} 察觉到\n对方的特性！"),    // 0x8df6ca2
    [197] = COMPOUND_STRING("急剧"),    // 0x8df6ef7
    [198] = COMPOUND_STRING("提升！"),    // 0x8df6f00
    [199] = COMPOUND_STRING("大幅"),    // 0x8df6f06
    [200] = COMPOUND_STRING("下降！"),    // 0x8df6f0f
    [201] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}的{B_BUFF1}\n{B_BUFF2}"),    // 0x8df6f15
    [202] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}的{B_BUFF1}\n{B_BUFF2}"),    // 0x8df6f20
    [203] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}的{B_BUFF1}\n{B_BUFF2}"),    // 0x8df6f45
    [204] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}的{B_BUFF1}\n{B_BUFF2}"),    // 0x8df6f50
    [205] = COMPOUND_STRING("命中要害！"),    // 0x8df6f9a
    [206] = COMPOUND_STRING("一击必杀！"),    // 0x8df6faa
    [207] = COMPOUND_STRING("{PAUSE 32}1，{PAUSE 15}2，然后{PAUSE 15}… {PAUSE 15}… {PAUSE 15}… {PAUSE 15}{PLAY_SE SE_BALL_BOUNCE_1}叮咚！\p"),    // 0x8df6fbd
    [208] = COMPOUND_STRING("那⋯\p"),    // 0x8df6fe9
    [209] = COMPOUND_STRING("收效甚微…"),    // 0x8df7011
    [210] = COMPOUND_STRING("效果拔群！"),    // 0x8df702a
    [211] = COMPOUND_STRING("{PLAY_SE SE_FLEE}成功逃走了！\p"),    // 0x8df7040
    [212] = COMPOUND_STRING("{PLAY_SE SE_FLEE}野生的{B_BUFF1}逃走了！"),    // 0x8df7088
    [213] = COMPOUND_STRING("不可以！\n训练家要堂堂正正地面对战斗！\p"),    // 0x8df7169
    [214] = COMPOUND_STRING("不能逃跑！\p"),    // 0x8df7198
    [215] = COMPOUND_STRING("小田卷博士:不要像那样不管我！\p"),    // 0x8df71a7
    [216] = COMPOUND_STRING("但是什么都没发生！"),    // 0x8df71cf
    [217] = COMPOUND_STRING("但是它失败了！"),    // 0x8df71e5
    [218] = COMPOUND_STRING("因混乱对自己\n造成了伤害！"),    // 0x8df71f4
    [219] = COMPOUND_STRING("鹦鹉学舌失败了！"),    // 0x8df7215
    [220] = COMPOUND_STRING("下起了雨！"),    // 0x8df722d
    [221] = COMPOUND_STRING("下起了大雨！"),    // 0x8df7241
    [222] = COMPOUND_STRING("雨一直在下。"),    // 0x8df7255
    [223] = COMPOUND_STRING("大雨一直在下。"),    // 0x8df726d
    [224] = COMPOUND_STRING("雨不再下了。"),    // 0x8df7285
    [225] = COMPOUND_STRING("扬起了沙暴！"),    // 0x8df7297
    [226] = COMPOUND_STRING("飞沙走石。"),    // 0x8df72ab
    [227] = COMPOUND_STRING("沙暴停止了。"),    // 0x8df72c0
    [228] = COMPOUND_STRING("阳光变猛烈了！"),    // 0x8df72d8
    [229] = COMPOUND_STRING("阳光很猛烈。"),    // 0x8df72f1
    [230] = COMPOUND_STRING("阳光不再猛烈。"),    // 0x8df7309
    [231] = COMPOUND_STRING("下起了冰雹！"),    // 0x8df731d
    [232] = COMPOUND_STRING("冰雹还在持续。"),    // 0x8df7331
    [233] = COMPOUND_STRING("冰雹停止了。"),    // 0x8df7349
    [234] = COMPOUND_STRING("无法使出喷出！"),    // 0x8df735b
    [235] = COMPOUND_STRING("无法使出吞下！"),    // 0x8df737d
    [236] = COMPOUND_STRING("风变成\n热风了"),    // 0x8df739f
    [237] = COMPOUND_STRING("能力等级\n都还原成初始状态了！"),    // 0x8df73c1
    [238] = COMPOUND_STRING("钱币散落一地！"),    // 0x8df73e3
    [239] = COMPOUND_STRING("HP太低了，\n以致无法制造替身！"),    // 0x8df73ff
    [240] = COMPOUND_STRING("平分了双方的HP！"),    // 0x8df7425
    [241] = COMPOUND_STRING("铃铛响了起来！"),    // 0x8df7445
    [242] = COMPOUND_STRING("受到影响的宝可梦\n将在3回合内倒下！"),    // 0x8df7454
    [243] = COMPOUND_STRING("该招式没有PP，\n无法使用！\p"),    // 0x8df7484
    [244] = COMPOUND_STRING("但是该招式没有PP！"),    // 0x8df74a7
    [245] = COMPOUND_STRING("{B_PLAYER_NAME}使用\n{B_LAST_ITEM}！"),    // 0x8df79d0
    [246] = COMPOUND_STRING("满充使用了\n{B_LAST_ITEM}！"),    // 0x8df79dc
    [247] = COMPOUND_STRING("训练家挡下了精灵球！"),    // 0x8df79fa
    [248] = COMPOUND_STRING("不要做小偷！"),    // 0x8df7a18
    [249] = COMPOUND_STRING("它躲开了精灵球！\n这只宝可梦不能被收服！"),    // 0x8df7a2a
    [250] = COMPOUND_STRING("你错过了这只宝可梦！"),    // 0x8df7a63
    [251] = COMPOUND_STRING("哦，不！\n宝可梦逃走了！"),    // 0x8df7a7b
    [252] = COMPOUND_STRING("啊！\n似乎要被抓住了！"),    // 0x8df7a9b
    [253] = COMPOUND_STRING("哎呀！\n再加把劲！"),    // 0x8df7aba
    [254] = COMPOUND_STRING("可恶！\n差一点就抓到了！"),    // 0x8df7ad0
    [255] = COMPOUND_STRING("搞定！\n{B_DEF_NAME}被收服了！{WAIT_SE}{PLAY_BGM MUS_CAUGHT}\p"),    // 0x8df7aed
    [256] = COMPOUND_STRING("搞定！\n{B_DEF_NAME}被收服了！{WAIT_SE}{PLAY_BGM MUS_CAUGHT}{PAUSE 127}"),    // 0x8df7b0b
    [257] = COMPOUND_STRING("要给{B_DEF_NAME}取一个昵称么？"),    // 0x8df7b2b
    [258] = COMPOUND_STRING("{B_DEF_NAME}被送到了\n{B_PC_CREATOR_NAME}电脑。"),    // 0x8df7b4f
    [259] = COMPOUND_STRING("{B_DEF_NAME}的数据\n登记到了宝可梦图鉴。\p"),    // 0x8df7b79
    [260] = COMPOUND_STRING("现在在下雨。"),    // 0x8df7b9e
    [261] = COMPOUND_STRING("沙暴很猛烈。"),    // 0x8df7bad
    [262] = COMPOUND_STRING("逃不掉！\p"),    // 0x8df58cd
    [263] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}在睡眠时\n无法听从命令！"),    // 0x8df74ce
    [264] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}无法\n听从命令！"),    // 0x8df74ee
    [265] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}开始打盹了！"),    // 0x8df7501
    [266] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}在\n周围闲逛！"),    // 0x8df7512
    [267] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}不\n听从命令！"),    // 0x8df7528
    [268] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}转身离开！"),    // 0x8df7537
    [269] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}假装\n没有注意到！"),    // 0x8df7547
    [270] = COMPOUND_STRING("{B_TRAINER1_CLASS} {B_TRAINER1_NAME}\n就要换上{B_BUFF2}了。\p{B_PLAYER_NAME}要替换\n宝可梦吗？"),    // 0x8df7563
    [271] = COMPOUND_STRING("{B_PLAYER_NAME}悄悄靠近了\n{B_OPPONENT_MON1_NAME}！"),    // 0x8df75bc
    [272] = COMPOUND_STRING("{B_PLAYER_NAME}不能再靠近了！"),    // 0x8df75d3
    [273] = COMPOUND_STRING("{B_OPPONENT_MON1_NAME}小心地\n注视着！"),    // 0x8df75ec
    [274] = COMPOUND_STRING("{B_OPPONENT_MON1_NAME}对\n{B_BUFF1}感到好奇！"),    // 0x8df7606
    [275] = COMPOUND_STRING("{B_OPPONENT_MON1_NAME}被\n{B_BUFF1}迷倒了！"),    // 0x8df7622
    [276] = COMPOUND_STRING("{B_OPPONENT_MON1_NAME}完全忽视了\n{B_BUFF1}！"),    // 0x8df763e
    [277] = COMPOUND_STRING("{B_PLAYER_NAME}朝{B_OPPONENT_MON1_NAME}投掷了\n{POKEBLOCK}！"),    // 0x8df765c
    [278] = COMPOUND_STRING("{PLAY_SE SE_DING_DONG}提示:\n你用完了原野球！游戏结束！\p"),    // 0x8df7678
    [279] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}的{B_LAST_ITEM}\n治愈了麻痹！"),    // 0x8df7c04
    [280] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}的{B_LAST_ITEM}\n治愈了中毒！"),    // 0x8df7c1d
    [281] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}的{B_LAST_ITEM}\n治愈了烧伤！"),    // 0x8df7c33
    [282] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}的{B_LAST_ITEM}\n解除了冰冻！"),    // 0x8df7c4c
    [283] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}的{B_LAST_ITEM}\n让它从睡眠中苏醒了！"),    // 0x8df7c62
    [284] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}的{B_LAST_ITEM}\n使它解除了混乱！"),    // 0x8df7c82
    [285] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}的{B_LAST_ITEM}\n治愈了它的{B_BUFF1}状态！"),    // 0x8df7ca7
    [286] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}的{B_LAST_ITEM}\n恢复了HP！"),    // 0x8df7ce4
    [287] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}的{B_LAST_ITEM}\n恢复了{B_BUFF1}的PP！"),    // 0x8df7cfd
    [288] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}的{B_LAST_ITEM}\n治愈了异常状态！"),    // 0x8df7d17
    [289] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}的{B_LAST_ITEM}\n稍微恢复了HP！"),    // 0x8df7d34
    [290] = COMPOUND_STRING("{B_LAST_ITEM}只允许\n使用{B_CURRENT_MOVE}！\p"),    // 0x8df7d56
    [291] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}靠它的\n{B_LAST_ITEM}顶住了！"),    // 0x8df7d75
    [292] = COMPOUND_STRING(""),    // 0x8df7d8e
    [293] = COMPOUND_STRING("{B_EFF_NAME_WITH_PREFIX}的{B_EFF_ABILITY}\n防止了烧伤！"),    // 0x8df6cc0
    [294] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}的{B_DEF_ABILITY}\n阻止了{B_CURRENT_MOVE}！"),    // 0x8df6cd8
    [295] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}的{B_ATK_ABILITY}\n使HP稍微恢复了！"),    // 0x8df6cfe
    [296] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}的{B_SCR_ACTIVE_ABILITY}\n在场上扬起了沙暴！"),    // 0x8df6d20
    [297] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}的{B_SCR_ACTIVE_ABILITY}\n防止了{B_BUFF1}下降！"),    // 0x8df6d64
    [298] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}的{B_DEF_ABILITY}\n迷倒了{B_ATK_NAME_WITH_PREFIX}！"),    // 0x8df6d7e
    [299] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}的{B_DEF_ABILITY}\n使{B_CURRENT_MOVE}无效化了！"),    // 0x8df6d95
    [300] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}的{B_SCR_ACTIVE_ABILITY}\n治愈了{B_BUFF1}！"),    // 0x8df6db2
    [301] = COMPOUND_STRING("吸收了黏液！"),    // 0x8df6dd0
    [302] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}变身了！"),    // 0x8df6dee
    [303] = COMPOUND_STRING("电的力量\n减弱了！"),    // 0x8df6904
    [304] = COMPOUND_STRING("火的力量\n减弱了！"),    // 0x8df6926
    [305] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}潜入水中！"),    // 0x8df5e81
    [306] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}跳了起来！"),    // 0x8df5e94
    [307] = COMPOUND_STRING("暂时无法忘记秘传招式。\p"),    // 0x8df6fef
    [308] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}发现了\n一个{B_LAST_ITEM}！"),    // 0x8df6941
    [309] = COMPOUND_STRING("你打败了\n{B_TRAINER1_CLASS} {B_TRAINER1_NAME}！\p"),    // 0x8df75a4
    [310] = COMPOUND_STRING("一股沁心的香气\n弥漫了开来！"),    // 0x8df6952
    [311] = COMPOUND_STRING("道具暂不起作用。{PAUSE 64}"),    // 0x8df697c
    [312] = COMPOUND_STRING("对于{B_SCR_ACTIVE_NAME_WITH_PREFIX}，\n{B_LAST_ITEM} {B_BUFF1} 。"),    // 0x8df6998
    [313] = COMPOUND_STRING("使用了{B_LAST_ITEM}，{B_BUFF1}\n的{B_SCR_ACTIVE_NAME_WITH_PREFIX}{B_BUFF2}"),    // 0x8df6f2b//不确定
    [314] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}使用了\n{B_LAST_ITEM}来变得兴奋！"),    // 0x8df69a6
    [315] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}的{B_DEF_ABILITY}\n使{B_CURRENT_MOVE}无效了！"),    // 0x8df6b76
    [316] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}被困于\n流沙地狱中！"),    // 0x8df5ede
    [317] = COMPOUND_STRING(""),    // 0x8df55fc
    [318] = COMPOUND_STRING("提升"),    // 0x8df55fd
    [319] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}的{B_SCR_ACTIVE_ABILITY}\n使阳光更加强烈！"),    // 0x8df6d40
    [320] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}因{B_DEF_ABILITY}\n抵御了地上系招式！"),    // 0x8df5729
    [321] = COMPOUND_STRING("现在要扔出精灵球了是吧？\n我…我会全力以赴！"),    // 0x8df7d8f
    [322] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}的{B_DEF_ABILITY}\n承受了攻击！"),    // 0x8df6dfe
    [323] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}准备和\n{B_CURRENT_MOVE}一同倒下！"),    // 0x8df65b7
    [324] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}失去了焦点\n不能出招！"),    // 0x8df69c0
    [325] = COMPOUND_STRING("使用下个宝可梦？"),    // 0x8df56d3
    [326] = COMPOUND_STRING("{PLAY_SE SE_FLEE}{B_ATK_NAME_WITH_PREFIX}\n使用了{B_LAST_ITEM}后逃走了！\p"),    // 0x8df7056
    [327] = COMPOUND_STRING("{PLAY_SE SE_FLEE}{B_ATK_NAME_WITH_PREFIX}\n使用了{B_ATK_ABILITY}后逃走了！\p"),    // 0x8df7071
    [328] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}被\n拖入了战斗！\p"),    // 0x8df69e5
    [329] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}的{B_DEF_ABILITY}\n防止了{B_SCR_ACTIVE_NAME_WITH_PREFIX}的\l{B_BUFF1}起作用！"),    // 0x8df6e34
    [330] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}的{B_LAST_ITEM}\n使其恢复正常了！"),    // 0x8df7cc5
    [331] = COMPOUND_STRING("{B_TRAINER1_CLASS} {B_TRAINER1_NAME}\n使用{B_LAST_ITEM}！"),    // 0x8df79eb
    [332] = COMPOUND_STRING("盒子已经满了！\n不能再收服更多了！\p"),    // 0x8df7bc4
    [333] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}\n避免了攻击！"),    // 0x8df574d
    [334] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}的{B_SCR_ACTIVE_ABILITY}\n使其无效！"),    // 0x8df6e5c
    [335] = COMPOUND_STRING("{B_EFF_NAME_WITH_PREFIX}的{B_EFF_ABILITY}\n防止了畏缩！"),    // 0x8df6e79
    [336] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}\n已经烧伤了。"),    // 0x8df5a2a
    [337] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}的能力\n不能再降低了！"),    // 0x8df6f7b
    [338] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}的{B_SCR_ACTIVE_ABILITY}\n阻止了{B_CURRENT_MOVE}！"),    // 0x8df6ceb
    [339] = COMPOUND_STRING("{B_ATK_PREFIX1}的{B_BUFF1}\n已关闭！"),    // 0x8df6011
    [340] = COMPOUND_STRING("{B_ATK_PREFIX2}的{B_CURRENT_MOVE}\n稍微提升了防御！"),    // 0x8df5d46
    [341] = COMPOUND_STRING("{B_ATK_PREFIX2}的{B_CURRENT_MOVE}\n稍微提升了特防！"),    // 0x8df5d0d
    [342] = COMPOUND_STRING("墙壁粉碎了！"),    // 0x8df69fa
    [343] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}的{B_ATK_ABILITY}\n阻止了{B_DEF_NAME_WITH_PREFIX}的\l{B_DEF_ABILITY}发动作用！"),    // 0x8df6e95
    [344] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}的{B_SCR_ACTIVE_ABILITY}\n解决了{B_BUFF1}的问题！"),    // 0x8df6ebc
    [345] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}逃不掉"),    // 0x8df58dc
    [346] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}获得了\n{B_BUFF1}。"),    // 0x8df66e6
    [347] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}获得了\n{B_BUFF2}。"),    // 0x8df66f6
    [348] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}获得了\n{B_BUFF1}。\p{B_DEF_NAME_WITH_PREFIX}获得了\n{B_BUFF2}。"),    // 0x8df6706
    [349] = COMPOUND_STRING("但是它没有效果！"),    // 0x8df6a0e
    [350] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}的{B_SCR_ACTIVE_ABILITY}\n对{B_EFF_NAME_WITH_PREFIX}没有影响。"),    // 0x8df6eda
    [351] = COMPOUND_STRING("{B_TRAINER1_CLASS} {B_TRAINER1_NAME}和\n{B_TRAINER2_CLASS} {B_TRAINER2_NAME}\l被击败了\p"),    // 0x8dfa9bf
    [352] = COMPOUND_STRING("{B_TRAINER2_LOSE_TEXT}"),    // 0x8dfa9df
    [353] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}似乎\n无法使用它的力量！"),    // 0x8dfa9e2
    [354] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}的眼中\n闪烁着光芒！"),    // 0x8dfaa0b
    [355] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}\n正在就位！"),    // 0x8dfaa29
    [356] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}开始发出低沉的咆哮！"),    // 0x8dfaa46
    [357] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}想要更多！"),    // 0x8dfaa60
    [358] = COMPOUND_STRING("在裁判的判定下,\n{B_PLAYER_MON1_NAME}击败了\p对手{B_OPPONENT_MON1_NAME}！"),    // 0x8dfac73
    [359] = COMPOUND_STRING("在裁判的判定下,\n{B_PLAYER_MON1_NAME}输给了\p对手{B_OPPONENT_MON1_NAME}！"),    // 0x8dfaca8
    [360] = COMPOUND_STRING("{B_PLAYER_MON1_NAME}和对手\n{B_OPPONENT_MON1_NAME}在裁判的判定下\p打成平手！"),    // 0x8dfacdc
    [361] = COMPOUND_STRING("您想放弃比赛\n并立即退出吗？"),    // 0x8dfad58
    [362] = COMPOUND_STRING("{B_PLAYER_NAME}输掉了比赛！"),    // 0x8dfad8a
    [363] = COMPOUND_STRING("{B_COPY_VAR_2}被转移到\n某人的电脑，\p它被放置在\n盒子“{B_COPY_VAR_1}中。”"),    // 0x82ec3aa
    [364] = COMPOUND_STRING("{B_COPY_VAR_2}被转移到\n真由美的电脑，\p它被放置在\n盒子“{B_COPY_VAR_1}中。”"),    // 0x82ec3ea
    [365] = COMPOUND_STRING("某人电脑上的盒子“{B_COPY_VAR_3}” 已满\n。{B_COPY_VAR_2}被转移到\p盒子“{B_COPY_VAR_1}。”"),    // 0x82ec42a
    [366] = COMPOUND_STRING("真由美电脑上的盒子“{B_COPY_VAR_3}” 已满\n。{B_COPY_VAR_2}被转移到\p盒子“{B_COPY_VAR_1}。”"),    // 0x82ec46d
    [367] = COMPOUND_STRING("{B_TRAINER1_WIN_TEXT}"),    // 0x8dfada2
    [368] = COMPOUND_STRING("{B_TRAINER2_WIN_TEXT}"),    // 0x8dfada5
    [369] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}的{B_DEF_ABILITY}\n承受了攻击！"),    // 0x8df7dc0
    [370] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}由于{B_LAST_ITEM}\n而完全充能！"),    // 0x8df7ddd
    [371] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}被它的{B_LAST_ITEM}\n伤害了！"),    // 0x8df7e04
    [372] = COMPOUND_STRING("{B_EFF_NAME_WITH_PREFIX}由于{B_LAST_ITEM}\n中了剧毒！"),    // 0x8df7e1b
    [373] = COMPOUND_STRING("{B_EFF_NAME_WITH_PREFIX}由于{B_LAST_ITEM}\n烧伤了！"),    // 0x8df7e3d
    [374] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}的{B_DEF_ABILITY}\n激活了！"),    // 0x8df7e56
    [375] = COMPOUND_STRING("重力加强了！"),    // 0x8df7e69
    [376] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}被\n识破了！"),    // 0x8df7e7e
    [377] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}醒了！"),    // 0x8df7e92
    [378] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}偷到并\n吃掉了{B_DEF_NAME_WITH_PREFIX}的{B_LAST_ITEM}！"),    // 0x8df7e9e
    [379] = COMPOUND_STRING("{B_ATK_TEAM2}的身后\n吹起了顺风！"),    // 0x8df7eb8
    [380] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}回\n到{B_ATK_TRAINER_CLASS}{B_ATK_TRAINER_NAME}"),    // 0x8df7edf
    [381] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}不能使用\n道具了！"),    // 0x8df7ef5
    [382] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}扔掉了\n{B_LAST_ITEM}！"),    // 0x8df7f11
    [383] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}被阻止\n回复！"),    // 0x8df7f22
    [384] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}交换了它的\n攻击和防御！"),    // 0x8df7f41
    [385] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}的特性\n被压制了！"),    // 0x8df7f65
    [386] = COMPOUND_STRING("{B_CURRENT_MOVE}保护{B_ATK_TEAM2}\n的队伍不被击中要害！"),    // 0x8df7f82
    [387] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}与目标交换了\n攻击和\p和特攻！"),    // 0x8df7fae
    [388] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}与目标交换了\n防御和\p和特防！"),    // 0x8df7ff5
    [389] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}获得了\n{B_DEF_ABILITY}！"),    // 0x8df803d
    [390] = COMPOUND_STRING("毒菱散落在\n对方队伍的脚下！"),    // 0x8df804d
    [391] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}与目标交换了\n能力等级！"),    // 0x8df808f
    [392] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}身边围绕着\n一层水幕！"),    // 0x8df80b9
    [393] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}通过电磁力\n漂浮了起来！"),    // 0x8df80e4
    [394] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}扭曲了\n时空！"),    // 0x8df8106
    [395] = COMPOUND_STRING("尖锐的岩石漂浮在了\n {B_DEF_TEAM2} 的队伍周围！"),    // 0x8df8121
    [396] = COMPOUND_STRING("被神秘的月光\n笼罩！"),    // 0x8df8151
    [397] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} 被\n旋转的岩浆困住了！"),    // 0x8df817a
    [398] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} 突然\n消失了！"),    // 0x8df819f
    [399] = COMPOUND_STRING("{B_CURRENT_MOVE} 保护了\n{B_ATK_TEAM2} 的队伍！"),    // 0x8df81b6
    [400] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} 与目标\n平分了防御！"),    // 0x8df81cc
    [401] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} 与目标\n平分了攻击！"),    // 0x8df81f1
    [402] = COMPOUND_STRING("制造出了\n防御与特防能力值互换的奇妙空间！"),    // 0x8df8216
    [403] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} 变得灵活了！"),    // 0x8df8263
    [404] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} 被投向了\n空中！"),    // 0x8df8275
    [405] = COMPOUND_STRING("制造出了\n道具无效的魔法空间！"),    // 0x8df8291
    [406] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} 被\n击落！"),    // 0x8df82dd
    [407] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} 变成了\n水属性！"),    // 0x8df82f4
    [408] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} 获得了\n单纯！"),    // 0x8df8318
    [409] = COMPOUND_STRING(""),    // 0x8df55fc
    [410] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}\n接受了好意！"),    // 0x8df832c
    [411] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}的能力\n被清除了！"),    // 0x8df8344
    [412] = COMPOUND_STRING(""),    // 0x8df55fc
    [413] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} 和\n{B_SCR_ACTIVE_NAME_WITH_PREFIX} 交换了位置！"),    // 0x8df8364
    [414] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}的HP回复了！"),    // 0x8df837f
    [415] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} 把\n{B_DEF_NAME_WITH_PREFIX} 抓向天空！"),    // 0x8df8395
    [416] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} 从自由落体状态\n逃脱了！"),    // 0x8df83ae
    [417] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}的行动\n延后了！"),    // 0x8df83ce
    [418] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}的属性\n变成了 {B_DEF_NAME_WITH_PREFIX}！"),    // 0x8df83e7
    [419] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} 收到了 {B_LAST_ITEM}\n来自 {B_ATK_NAME_WITH_PREFIX}"),    // 0x8df840c
    [420] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}可以\n再次使用道具了！"),    // 0x8df8423
    [421] = COMPOUND_STRING("电磁飘浮"),    // 0x8df843b
    [422] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}的{B_BUFF1}\n解除了！"),    // 0x8df844c//不确定
    [423] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}从意念移物\n状态中逃脱了！"),    // 0x8df8482
    [424] = COMPOUND_STRING("{B_ATK_TEAM1}队伍的顺风\n停止了！"),    // 0x8df84a5
    [425] = COMPOUND_STRING("{B_ATK_TEAM1}队伍的幸运咒语\n结束了！"),    // 0x8df84c6
    [426] = COMPOUND_STRING("扭曲的空间\n复原了！"),    // 0x8df84e7
    [427] = COMPOUND_STRING("奇妙空间结束了,防御\n与特防能力值恢复了正常！"),    // 0x8df8512
    [428] = COMPOUND_STRING("魔法空间结束了,道具\n效果恢复了正常！"),    // 0x8df855a
    [429] = COMPOUND_STRING("玩泥巴的效果消失了。"),    // 0x8df859b
    [430] = COMPOUND_STRING("玩水的效果消失了。"),    // 0x8df85c0
    [431] = COMPOUND_STRING("重力恢复了正常！"),    // 0x8df85e7
    [432] = COMPOUND_STRING("水流环回复了\n{B_ATK_NAME_WITH_PREFIX}的HP！"),    // 0x8df8603
    [433] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}的{B_DEF_ABILITY}\n消失了！"),    // 0x8df867c
    [434] = COMPOUND_STRING("脚下的电光\n不见了！"),    // 0x8df868e
    [435] = COMPOUND_STRING("脚下的雾气\n不见了！"),    // 0x8df86c0
    [436] = COMPOUND_STRING("脚下奇妙的感觉\n不见了！"),    // 0x8df86eb
    [437] = COMPOUND_STRING("脚下的青草\n不见了！"),    // 0x8df871b
    [438] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}的{B_DEF_ABILITY}\n提升了它的{B_BUFF1}！"),    // 0x8df861f
    [439] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}的{B_DEF_ABILITY}\n将攻击提升至最大！"),    // 0x8df8747
    [440] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}的{B_ATK_ABILITY}\n提升了它的{B_BUFF1}！"),    // 0x8df864e
    [441] = COMPOUND_STRING("毒素回复了{B_ATK_NAME_WITH_PREFIX}\n的少量体力！"),    // 0x8df8761
    [442] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}正在被\n{B_ATK_ABILITY}\n折磨！"),    // 0x8df879f
    [443] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}打破了常规！"),    // 0x8df87b6
    [444] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}正在释放\n溅射气场！"),    // 0x8df87ca
    [445] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}正在释放\n炽热气场！"),    // 0x8df87ec
    [446] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}无法展开行动！"),    // 0x8df880c
    [447] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}最终聚集了\n它所有的力量！"),    // 0x8df8823
    [448] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}的{B_ATK_ABILITY}\n受到了伤害！"),    // 0x8df8844
    [449] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}受伤了！"),    // 0x8df8860
    [450] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}发抖了！"),    // 0x8df886c
    [451] = COMPOUND_STRING("{B_SCR_ACTIVE_ABILITY}提醒{B_SCR_ACTIVE_NAME_WITH_PREFIX}\n注意{B_DEF_NAME_WITH_PREFIX}的{B_BUFF1}！"),    // 0x8df888a
    [452] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}的{B_ATK_ABILITY}\n回复了少量体力！"),    // 0x8df88a8
    [453] = COMPOUND_STRING("开始下冰雹了！"),    // 0x8df88c8
    [454] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}察觉到了{B_DEF_NAME_WITH_PREFIX}\n的{B_LAST_ITEM}！"),    // 0x8df88dc
    [455] = COMPOUND_STRING("对手的队伍太紧张以致于\n无法吃下树果！"),    // 0x8df88fc
    [456] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}收获了\n它的{B_LAST_ITEM}！"),    // 0x8df892d
    [457] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}的{B_ATK_ABILITY}提升了攻击！"),    // 0x8df8942
    [458] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}弹回了\n{B_ATK_NAME_WITH_PREFIX}！"),    // 0x8df895d
    [459] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}的{B_ATK_ABILITY}变身\n成了{B_BUFF1}属性！"),    // 0x8df8979
    [460] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}通过{B_ATK_ABILITY}把它的{B_LAST_ITEM}\n传递给{B_SCR_ACTIVE_NAME_WITH_PREFIX}！"),    // 0x8df89a2
    [461] = COMPOUND_STRING("锋利的岩石扎进了对手的\n{B_SCR_ACTIVE_NAME_WITH_PREFIX}！"),    // 0x8df89c5
    [462] = COMPOUND_STRING("毒菱从对方的队伍\n周围消失了！"),    // 0x8df89e1
    [463] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}中毒了！"),    // 0x8df8a25
    [464] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}陷入了\n黏黏网！"),    // 0x8df8a36
    [465] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}的\n治愈愿望成真了！"),    // 0x8df8a55
    [466] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}恢复了健康！"),    // 0x8df8a78
    [467] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}被神秘的月光\n笼罩！"),    // 0x8df8a8c
    [468] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}的{B_BUFF1}被{B_DEF_NAME_WITH_PREFIX}的{B_DEF_ABILITY}定住了！"),    // 0x8df8ab5
    [469] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}获得了{B_LAST_ABILITY}！"),    // 0x8df8ad6
    [470] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}的{B_DEF_ABILITY}\n降低了其{B_BUFF1}！"),    // 0x8df8636
    [471] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}的{B_BUFF1}\n不能变得更高了！"),    // 0x8df8ae6
    [472] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}的{B_CURRENT_MOVE}被\n{B_DEF_NAME_WITH_PREFIX}的\l{B_DEF_ABILITY}弹回了！"),    // 0x8df8aff
    [473] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}变身成了\n{B_DEF_NAME_WITH_PREFIX}并发动了{B_LAST_ABILITY}！"),    // 0x8df8b24
    [474] = COMPOUND_STRING("{B_LAST_ITEM}阻止了\n变化招式的使用！\p"),    // 0x8df8d1e
    [475] = COMPOUND_STRING("由于重力，{B_ATK_NAME_WITH_PREFIX}\n不能使用{B_CURRENT_MOVE}\p"),    // 0x8df8d5b
    [476] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} 无法\n使用治愈招式！\p"),    // 0x8df8d80
    [477] = COMPOUND_STRING("此招式效果还未完成\p"),    // 0x8df8b45
    [478] = COMPOUND_STRING("一张黏黏网展开在了{B_DEF_TEAM2}队伍的周围！"),    // 0x8df8bb7
    [479] = COMPOUND_STRING("对方{B_ATK_NAME_WITH_PREFIX}的行动延后了！"),    // 0x8df8bee
    [480] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}清除了\n毒菱！"),    // 0x8df8b68
    [481] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}清除了\n黏黏网！"),    // 0x8df8b83
    [482] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}清除了\n隐形岩！"),    // 0x8df8b9c
    [483] = COMPOUND_STRING("离子风暴正在\n肆虐！"),    // 0x8df8c14
    [484] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}的能力\n变化全部都被反转了！"),    // 0x8df8c3e
    [485] = COMPOUND_STRING("脚下雾气缭绕！"),    // 0x8df8c63
    [486] = COMPOUND_STRING("脚下绿草如茵！"),    // 0x8df8c87
    [487] = COMPOUND_STRING("脚下电光飞闪！"),    // 0x8df8cac
    [488] = COMPOUND_STRING("脚下传来了奇妙的感觉！"),    // 0x8df8cdd
    [489] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}的招式\n带电了！"),    // 0x8df8cf8
    [490] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}的{B_LAST_ITEM}对\n{B_ATK_TRAINER_NAME}的超级环有反应了！"),    // 0x8df8da0
    [491] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}\n超级进化了！"),    // 0x8df8dea
    [492] = COMPOUND_STRING("巨幅提升"),    // 0x8df8eac
    [493] = COMPOUND_STRING("巨幅下降"),    // 0x8df8eb9
    [494] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} 遭受着\n{B_ATK_NAME_WITH_PREFIX}的死缠烂打！"),    // 0x8df8ec3
    [495] = COMPOUND_STRING("对{B_DEF_NAME_WITH_PREFIX}\n没有效果！"),    // 0x8df8ef4
    [496] = COMPOUND_STRING("烈焰溅射到了\n {B_SCR_ACTIVE_NAME_WITH_PREFIX}！"),    // 0x8df8f0c
    [497] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}从{B_ATK_NAME_WITH_PREFIX}\n收到了{B_LAST_ITEM}！"),    // 0x8df8f28
    [498] = COMPOUND_STRING("{B_BUFF1}被附加到了\n{B_DEF_NAME_WITH_PREFIX}上！"),    // 0x8df8f40
    [499] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}\n被佯攻！"),    // 0x8df8f59//不确定
    [500] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}无法\n使用{B_CURRENT_MOVE}！"),    // 0x8df8f70
    [501] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}\n被粉尘覆盖！"),    // 0x8df8f82
    [502] = COMPOUND_STRING("宝可梦身上的粉尘\n被火焰碰到后爆炸了！"),    // 0x8df8f9b
    [503] = COMPOUND_STRING("无法使用打嗝！\p"),    // 0x8df8fda
    [504] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} 偷取了目标\n提升的能力！"),    // 0x8df8ff1
    [505] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} 因为重力\n不能停留空中！"),    // 0x8df9016
    [506] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} 的脚下\n雾气缭绕！"),    // 0x8df9041
    [507] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}因为青草场地\n恢复了少量HP！"),    // 0x8df906d
    [508] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}的脚下\n电光飞闪！"),    // 0x8df9091
    [509] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}的脚下\n传来了奇妙的感觉！"),    // 0x8df90bf
    [510] = COMPOUND_STRING("多亏了它的{B_LAST_ITEM}\n{B_DEF_NAME_WITH_PREFIX}没有起效果！"),    // 0x8df90e9
    [511] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}用花幕\n包裹了自己！"),    // 0x8df910e
    [512] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}用甜幕\n包裹了自己！"),    // 0x8df913a
    [513] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}被芳香幕\n保护了！"),    // 0x8df9169
    [514] = COMPOUND_STRING("祝贺, {B_PLAYER_NAME}！"),    // 0x8df918e
    [515] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}使用了\n{B_BUFF1}指示的招式！"),    // 0x8df91a3
    [516] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}可以再次\n使用声音招式了。"),    // 0x8df845e
    [517] = COMPOUND_STRING("由于地狱突刺，{B_ACTIVE_NAME_WITH_PREFIX}\n不能使用{B_CURRENT_MOVE}！\p"),    // 0x8df6ac9
    [518] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}\n高度集中！"),    // 0x8df91c6
    [519] = COMPOUND_STRING("{B_LAST_ITEM} 增强了\n{B_ATK_NAME_WITH_PREFIX}的力量！"),    // 0x8df91e1
    [520] = COMPOUND_STRING("{B_LAST_ITEM}为{B_DEF_NAME_WITH_PREFIX}\n减少了伤害！"),    // 0x8df91fd
    [521] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}吃掉了\n它的{B_LAST_ITEM}！"),    // 0x8df921b
    [522] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}用它的{B_LAST_ITEM}\n飘在了空中！"),    // 0x8df922a
    [523] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}的{B_LAST_ITEM}\n被打破了！"),    // 0x8df924c
    [524] = COMPOUND_STRING("{B_EFF_NAME_WITH_PREFIX}的{B_LAST_ITEM}\n被烧掉了！"),    // 0x8df925c
    [525] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} 偷走并吃掉了\n{B_EFF_NAME_WITH_PREFIX}的{B_LAST_ITEM}！"),    // 0x8df9272
    [526] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}的幻象\n被识破了！"),    // 0x8df928c
    [527] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} 治愈了\n{B_DEF_NAME_WITH_PREFIX}的问题！"),    // 0x8df92a4
    [528] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}\n燃尽了自己！"),    // 0x8df92bb
    [529] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}的{B_LAST_ABILITY}\n治愈了{B_SCR_ACTIVE_NAME_WITH_PREFIX}的问题！"),    // 0x8df92d1
    [530] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}的{B_SCR_ACTIVE_ABILITY}\n提升了{B_BUFF1}！"),    // 0x8df8665
    [531] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}的 {B_SCR_ACTIVE_ABILITY}\n被继承了！"),    // 0x8df92ed
    [532] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}\n正在吸收力量！"),    // 0x8df9305
    [533] = COMPOUND_STRING("在下一回合中\n没有宝可梦能够逃跑！"),    // 0x8df931c
    [534] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}\n因为{B_LAST_ITEM}而陷入爱河！"),    // 0x8df9352
    [535] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} 被冷光\n包围了！"),    // 0x8df936f
    [536] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}的 {B_BUFF1}\n没有被降低！"),    // 0x8df9396
    [537] = COMPOUND_STRING("{B_ATK_TRAINER_NAME}的热切愿望\n已经传达给了{B_ATK_NAME_WITH_PREFIX}！"),    // 0x8df8dc8
    [538] = COMPOUND_STRING("天气的影响消失了！"),    // 0x8df93af
    [539] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}正在施加\n压迫感！"),    // 0x8df93d3
    [540] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}正在释放\n暗黑气场！"),    // 0x8df93f0
    [541] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}正在释放\n妖精气场！"),    // 0x8df940d
    [542] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}反转了所有\n其它宝可梦的气场！"),    // 0x8df942b
    [543] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}正在打瞌睡！"),    // 0x8df9452
    [544] = COMPOUND_STRING("所有的墙都被\n清除了！"),    // 0x8df9462
    [545] = COMPOUND_STRING(""),    // 0x0
    [546] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}的{B_SCR_ACTIVE_ABILITY}\n提升了{B_BUFF1}！"),    // 0x8df9499
    [547] = COMPOUND_STRING("刮起了沙暴！"),    // 0x8df94b0
    [548] = COMPOUND_STRING("所有宝可梦都会在\n三回合后倒下！"),    // 0x8df94c7
    [549] = COMPOUND_STRING(""),    // 0x0
    [550] = COMPOUND_STRING(""),    // 0x0
    [551] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}同时\n具备两种特性！"),    // 0x8df9526
    [552] = COMPOUND_STRING("由于{B_DEF_NAME_WITH_PREFIX}的{B_SCR_ACTIVE_ABILITY}\n所有能力变化都还原了！"),    // 0x8df953c
    [553] = COMPOUND_STRING(""),    // 0x0
    [554] = COMPOUND_STRING(""),    // 0x0
    [555] = COMPOUND_STRING(""),    // 0x0
    [556] = COMPOUND_STRING(""),    // 0x0
    [557] = COMPOUND_STRING(""),    // 0x0
    [558] = COMPOUND_STRING(""),    // 0x0
    [559] = COMPOUND_STRING(""),    // 0x0
    [560] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}\n开始加热它的喙"),    // 0x8df9633
    [561] = COMPOUND_STRING("{B_PLAYER_NAME}已经没有可用的宝可梦了！\l在对战{B_TRAINER1_CLASS}\n{B_TRAINER1_NAME}时失败了！{PAUSE_UNTIL_PRESS}"),    // 0x8df57ec
    [562] = COMPOUND_STRING("{B_PLAYER_NAME}支付了{B_BUFF1}元作为奖金\n⋯⋯⋯⋯⋯\l{B_PLAYER_NAME}被击败了！\n{PAUSE_UNTIL_PRESS}"),    // 0x8df5826
    [563] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}改变形态！"),    // 0x8df9653
    [564] = COMPOUND_STRING("{B_ATK_ABILITY}\n只允许使用{B_CURRENT_MOVE}！\p"),    // 0x8df9663
    [565] = COMPOUND_STRING("由于与训练师的深厚羁绊,\n{B_ATK_NAME_WITH_PREFIX}蓄势待发！\p"),    // 0x8df9682
    [566] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}变成了\n小智版{B_BUFF1}！\p"),    // 0x8df96bd
    [567] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}\n掉落了它的{B_LAST_ITEM}！{WAIT_SE}\p"),    // 0x8df96d0
    [568] = COMPOUND_STRING("盒子已经满了。"),    // 0x8e19e1e
    [569] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}稍微\n回复了体力！"),    // 0x8df8787
    [570] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}逆转了\n属性相克效果！"),    // 0x8df8dff
    [571] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}的身体周围\n形成了一道保护罩！"),    // 0x8df8e23
    [572] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}\n制造了一个保护屏障！"),    // 0x8df8e46
    [573] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}的{B_SCR_ACTIVE_ABILITY}\n降低了{B_DEF_NAME_WITH_PREFIX}的特防！"),    // 0x8df8e66
    [574] = COMPOUND_STRING("一股奇怪的力量\n让每个人都昏昏欲睡！"),    // 0x8df8e84
    [575] = COMPOUND_STRING("整个团队都获得了一些经验值。\p"),    // 0x8df5573
    [576] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}\n造成了{B_BUFF1}点伤害！"),    // 0x8df9991
    [577] = COMPOUND_STRING("{B_ACTIVE_NAME_WITH_PREFIX}\n变成了{B_BUFF1}属性！"),    // 0x8df96e6
    [578] = COMPOUND_STRING("{B_ACTIVE_NAME_WITH_PREFIX}\n蓄势待发！"),    // 0x8df96fb
    [579] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}的{B_CURRENT_MOVE}\n提升了{B_BUFF1}！"),    // 0x8df9710
    [580] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}的{B_SCR_ACTIVE_ABILITY}\n压制了所有人的特性！"),    // 0x8df9727
    [581] = COMPOUND_STRING("得益于{B_ATK_ABILITY}，\n{B_ATK_NAME_WITH_PREFIX}再次发起了攻击！"),    // 0x8df974e
    [582] = COMPOUND_STRING("传说中的宝可梦{B_OPPONENT_MON1_NAME}\n已经准备好测试你了！"),    // 0x8df9776
    [583] = COMPOUND_STRING("{B_OPPONENT_MON1_NAME}的\n的所有属性都大幅提升了！"),    // 0x8df97a5
    [584] = COMPOUND_STRING("{B_OPPONENT_MON1_NAME}挡下了球！"),    // 0x8df97cb
    [585] = COMPOUND_STRING("尝试削弱\n{B_OPPONENT_MON1_NAME}的力量！"),    // 0x8df97e0
    [586] = COMPOUND_STRING("一股神秘的力量\n正包围着\p传说中的宝可梦{B_OPPONENT_MON1_NAME}！"),    // 0x8df9800
    [587] = COMPOUND_STRING("双方宝可梦都无法逃跑！"),    // 0x8df983c
    [588] = COMPOUND_STRING("由于{B_ATK_NAME_WITH_PREFIX}\n使用{B_CURRENT_MOVE}而无法逃跑！"),    // 0x8df985a
    [589] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}\n许下了一个愿望！"),    // 0x8df9886
    [590] = COMPOUND_STRING(""),    // 0x0
    [591] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}\n收走了场上所有物品！"),    // 0x8df9896
    [592] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}的{B_SCR_ACTIVE_ABILITY}\n提高了{B_BUFF1}！"),    // 0x8df94f0
    [593] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}与目标\n交换了特性！"),    // 0x8df98be
    [594] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}\n治愈了中毒！"),    // 0x8df98e4
    [595] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}被\n神秘的面纱守护着！"),    // 0x8df9903
    [596] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}的\n能力变化已重置！"),    // 0x8df9925
    [597] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}被诅咒了！"),    // 0x8df9947
    [598] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}改变\n成为{B_BUFF1}属性！"),    // 0x8df9956
    [599] = COMPOUND_STRING("{B_PLAYER_NAME}训练师招式\n等级提升至{LV} {B_COPY_VAR_1}！\p"),    // 0x8df55bb
    [600] = COMPOUND_STRING("{B_PLAYER_NAME}获得了\n{B_COPY_VAR_1}点训练师经验！\p"),    // 0x8df55dc
    [601] = COMPOUND_STRING("{B_PLAYER_NAME}\n赢得了{B_BUFF1}点BP\p"),    // 0x8df57c4
    [602] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}\n经历了英勇的变身！"),    // 0x8df996b

};