#include "global.h"

const u8 *const gBattleStringsTable[611] =
{
    [0] = COMPOUND_STRING("{B_TRAINER1_LOSE_TEXT}"),    // 0x8df5570
    [1] = COMPOUND_STRING("{B_BUFF1} gained{B_BUFF2}\n{B_BUFF3} Exp. Points!\p"),    // 0x8df559e
    [2] = COMPOUND_STRING("{B_BUFF1} grew to\nLV. {B_BUFF2}!{WAIT_SE}\p"),    // 0x8df5608
    [3] = COMPOUND_STRING("{B_BUFF1} learned\n{B_BUFF2}!{WAIT_SE}\p"),    // 0x8df561e
    [4] = COMPOUND_STRING("{B_BUFF1} is trying to\nlearn {B_BUFF2}.\p"),    // 0x8df5630
    [5] = COMPOUND_STRING("But, {B_BUFF1} can't learn\nmore than four moves.\p"),    // 0x8df564b
    [6] = COMPOUND_STRING("Delete a move to make\nroom for {B_BUFF2}?"),    // 0x8df5676
    [7] = COMPOUND_STRING("{B_BUFF1} forgot\n{B_BUFF2}.\p"),    // 0x8df5699
    [8] = COMPOUND_STRING("{PAUSE みStop learning\n{B_BUFF2}?"),    // 0x8df56a8
    [9] = COMPOUND_STRING("{B_BUFF1} did not learn\n{B_BUFF2}.\p"),    // 0x8df56bd
    [10] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} learned\n{B_BUFF1}!"),    // 0x8df7595
    [11] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}'s\nattack missed!"),    // 0x8df56e5
    [12] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}\nprotected itself!"),    // 0x8df56f9
    [13] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}'s stats won't\ngo any higher!"),    // 0x8df6f5b
    [14] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} avoided\ndamage with {B_DEF_ABILITY}!"),    // 0x8df570e
    [15] = COMPOUND_STRING("It doesn't affect\n{B_DEF_NAME_WITH_PREFIX}⋯"),    // 0x8df5764
    [16] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}\nfainted!\p"),    // 0x8df577a
    [17] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}\nfainted!\p"),    // 0x8df5787
    [18] = COMPOUND_STRING("{B_PLAYER_NAME} got ¥{B_BUFF1} and {B_BUFF2} Battle Point(s)\nfor winning!\p"),    // 0x8df5794
    [19] = COMPOUND_STRING("{B_PLAYER_NAME} is out of\nusable Pokémon!\p"),    // 0x8df585f
    [20] = COMPOUND_STRING("{B_PLAYER_NAME} panicked and lost ¥{B_BUFF1}⋯\p⋯ ⋯ ⋯ ⋯\p{B_PLAYER_NAME} whited out!{PAUSE_UNTIL_PRESS}"),    // 0x8df587d
    [21] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX} prevents\nescape with {B_SCR_ACTIVE_ABILITY}!\p"),    // 0x8df58b0
    [22] = COMPOUND_STRING("Hit {B_BUFF1} time(s)!"),    // 0x8df58ed
    [23] = COMPOUND_STRING("{B_EFF_NAME_WITH_PREFIX}\nfell asleep!"),    // 0x8df58fd
    [24] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_SCR_ACTIVE_ABILITY}\nmade {B_EFF_NAME_WITH_PREFIX} sleep!"),    // 0x8df590d
    [25] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} is\nalready asleep!"),    // 0x8df5924
    [26] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} is\nalready asleep!"),    // 0x8df593a
    [27] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}\nwasn't affected!"),    // 0x8df5950
    [28] = COMPOUND_STRING("{B_EFF_NAME_WITH_PREFIX}\nwas poisoned!"),    // 0x8df5964
    [29] = COMPOUND_STRING("{B_EFF_NAME_WITH_PREFIX} was poisoned by\n{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_BUFF1}!"),    // 0x8df5975
    [30] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} is hurt\nby poison!"),    // 0x8df5991
    [31] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} is already\npoisoned."),    // 0x8df59a7
    [32] = COMPOUND_STRING("{B_EFF_NAME_WITH_PREFIX} is badly\npoisoned!"),    // 0x8df59bf
    [33] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} had its\nenergy drained!"),    // 0x8df59d5
    [34] = COMPOUND_STRING("{B_EFF_NAME_WITH_PREFIX} was burned!"),    // 0x8df59f0
    [35] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_SCR_ACTIVE_ABILITY}\nburned {B_EFF_NAME_WITH_PREFIX}!"),    // 0x8df59ff
    [36] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} is hurt\nby its burn!"),    // 0x8df5a12
    [37] = COMPOUND_STRING("{B_EFF_NAME_WITH_PREFIX} was\nfrozen solid!"),    // 0x8df5a41
    [38] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_SCR_ACTIVE_ABILITY}\nfroze {B_EFF_NAME_WITH_PREFIX} solid!"),    // 0x8df5a56
    [39] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} is\nfrozen solid!"),    // 0x8df5a6e
    [40] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} was\ndefrosted!"),    // 0x8df5a82
    [41] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} was\ndefrosted!"),    // 0x8df5a94
    [42] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} was\ndefrosted by {B_CURRENT_MOVE}!"),    // 0x8df5aa6
    [43] = COMPOUND_STRING("{B_EFF_NAME_WITH_PREFIX} is paralyzed!\nIt may be unable to move!"),    // 0x8df5abe
    [44] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_SCR_ACTIVE_ABILITY}\nparalyzed {B_EFF_NAME_WITH_PREFIX}!\lIt may be unable to move!"),    // 0x8df5ae9
    [45] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} is paralyzed!\nIt can't move!"),    // 0x8df5b19
    [46] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} is\nalready paralyzed!"),    // 0x8df5b39
    [47] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} was\nhealed of paralysis!"),    // 0x8df5b52
    [48] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}'s\ndream was eaten!"),    // 0x8df5b6e
    [49] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}'s {B_BUFF1}\nwon't go higher!"),    // 0x8df5b84
    [50] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}'s {B_BUFF1}\nwon't go lower!"),    // 0x8df5b9d
    [51] = COMPOUND_STRING("Your team's {B_BUFF1}\nstopped working!"),    // 0x8df5bb5
    [52] = COMPOUND_STRING("The foe's {B_BUFF1}\nstopped working!"),    // 0x8df5bd5
    [53] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} is\nconfused!"),    // 0x8df5bf3
    [54] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} snapped\nout of confusion!"),    // 0x8df5c03
    [55] = COMPOUND_STRING("{B_EFF_NAME_WITH_PREFIX} became\nconfused!"),    // 0x8df5c20
    [56] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} is\nalready confused!"),    // 0x8df5c34
    [57] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}\nfell in love!"),    // 0x8df5c4c
    [58] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} is in love\nwith {B_SCR_ACTIVE_NAME_WITH_PREFIX}!"),    // 0x8df5c5d
    [59] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} is\nimmobilized by love!"),    // 0x8df5c74
    [60] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} was\nblown away!"),    // 0x8df5c8f
    [61] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} transformed\ninto the {B_BUFF1} type!"),    // 0x8df5ca2
    [62] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} flinched!"),    // 0x8df5cc3
    [63] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} regained\nhealth!"),    // 0x8df5cd0
    [64] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}'s\nHP is full!"),    // 0x8df5ce4
    [65] = COMPOUND_STRING("{B_ATK_PREFIX2}'s {B_CURRENT_MOVE}\nraised Sp. Def!"),    // 0x8df5cf5
    [66] = COMPOUND_STRING("{B_ATK_PREFIX2}'s {B_CURRENT_MOVE}\nraised Defense!"),    // 0x8df5d2e
    [67] = COMPOUND_STRING("{B_ATK_PREFIX2}'s party is covered\nby a veil!"),    // 0x8df5d67
    [68] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}'s party is protected\nby Safeguard!"),    // 0x8df5d88
    [69] = COMPOUND_STRING("{B_ATK_PREFIX3}'s party is no longer\nprotected by Safeguard!"),    // 0x8df5dae
    [70] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} went\nto sleep!"),    // 0x8df5dde
    [71] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} slept and\nbecame healthy!"),    // 0x8df5df0
    [72] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} whipped\nup a whirlwind!"),    // 0x8df5e0d
    [73] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} took\nin sunlight!"),    // 0x8df5e28
    [74] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} lowered\nits head!"),    // 0x8df5e3d
    [75] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} is glowing!"),    // 0x8df5e52
    [76] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} flew\nup high!"),    // 0x8df5e61
    [77] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} dug a hole!"),    // 0x8df5e72
    [78] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} was squeezed by\n{B_ATK_NAME_WITH_PREFIX}'s Bind!"),    // 0x8df5ea2
    [79] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} was trapped\nin the vortex!"),    // 0x8df5ec0
    [80] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} was wrapped by\n{B_ATK_NAME_WITH_PREFIX}!"),    // 0x8df5efb
    [81] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} clamped\n{B_DEF_NAME_WITH_PREFIX}!"),    // 0x8df5f11
    [82] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} is hurt\nby {B_BUFF1}!"),    // 0x8df5f20
    [83] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} was freed\nfrom {B_BUFF1}!"),    // 0x8df5f32
    [84] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} kept going\nand crashed!"),    // 0x8df5f48
    [85] = COMPOUND_STRING("{B_ATK_PREFIX2} became\nshrouded in Mist!"),    // 0x8df5f63
    [86] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX} is protected\nby Mist!"),    // 0x8df5f7f
    [87] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} is getting\npumped!"),    // 0x8df5f98
    [88] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} is hit\nwith recoil!"),    // 0x8df5fae
    [89] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} protected\nitself!"),    // 0x8df5fc5
    [90] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} is buffeted\nby the sandstorm!"),    // 0x8df5fda
    [91] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} is pelted\nby Hail!"),    // 0x8df5ffb
    [92] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} was seeded!"),    // 0x8df6023
    [93] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} evaded\nthe attack!"),    // 0x8df6032
    [94] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}'s health is\nsapped by Leech Seed!"),    // 0x8df6048
    [95] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} is fast\nasleep."),    // 0x8df606d
    [96] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} woke up!"),    // 0x8df6080
    [97] = COMPOUND_STRING("But {B_SCR_ACTIVE_NAME_WITH_PREFIX}'s Uproar\nkept it awake!"),    // 0x8df608c
    [98] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} woke up\nin the Uproar!"),    // 0x8df60ab
    [99] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} caused\nan Uproar!"),    // 0x8df60c5
    [100] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} is making\nan Uproar!"),    // 0x8df60da
    [101] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} calmed down."),    // 0x8df60f2
    [102] = COMPOUND_STRING("But {B_DEF_NAME_WITH_PREFIX} can't\nsleep in an Uproar!"),    // 0x8df6102
    [103] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} stockpiled\n{B_BUFF1}!"),    // 0x8df6123
    [104] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} can't\nStockpile any more!"),    // 0x8df6135
    [105] = COMPOUND_STRING("But {B_DEF_NAME_WITH_PREFIX} can't\nsleep in an Uproar!"),    // 0x8df6152
    [106] = COMPOUND_STRING("But the Uproar kept\n{B_DEF_NAME_WITH_PREFIX} awake!"),    // 0x8df6173
    [107] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} stayed awake\nusing its {B_DEF_ABILITY}!"),    // 0x8df6191
    [108] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} is storing\nenergy!"),    // 0x8df61af
    [109] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} unleashed\nenergy!"),    // 0x8df61c5
    [110] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} became\nconfused due to fatigue!"),    // 0x8df61da
    [111] = COMPOUND_STRING("{B_PLAYER_NAME} picked up\n¥{B_BUFF1}!\p"),    // 0x8df61fd
    [112] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} is\nunaffected!"),    // 0x8df6210
    [113] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} transformed\ninto {B_BUFF1}!"),    // 0x8df6222
    [114] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} made\na Substitute!"),    // 0x8df623a
    [115] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} already\nhas a Substitute!"),    // 0x8df6250
    [116] = COMPOUND_STRING("The Substitute took damage\nfor {B_DEF_NAME_WITH_PREFIX}!\p"),    // 0x8df626d
    [117] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}'s\nSubstitute faded!\p"),    // 0x8df6291
    [118] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} must\nrecharge!"),    // 0x8df62a9
    [119] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}'s Rage\nis building!"),    // 0x8df62bb
    [120] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}'s {B_BUFF1}\nwas disabled!"),    // 0x8df62d2
    [121] = COMPOUND_STRING("{B_ACTIVE_NAME_WITH_PREFIX}'s {B_CURRENT_MOVE}\nis disabled!\p"),    // 0x8df6a3b
    [122] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} is disabled\nno more!"),    // 0x8df62e8
    [123] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} got\nan Encore!"),    // 0x8df6300
    [124] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}'s Encore\nended!"),    // 0x8df6312
    [125] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} took aim\nat {B_DEF_NAME_WITH_PREFIX}!"),    // 0x8df6325
    [126] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} Sketched\n{B_BUFF1}!"),    // 0x8df6338
    [127] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} is trying\nto take its foe with it!"),    // 0x8df6348
    [128] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} took\n{B_ATK_NAME_WITH_PREFIX} with it!"),    // 0x8df636e
    [129] = COMPOUND_STRING("Reduced {B_DEF_NAME_WITH_PREFIX}'s\n{B_BUFF1} by {B_BUFF2}!"),    // 0x8df6382
    [130] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} stole\n{B_DEF_NAME_WITH_PREFIX}'s {B_LAST_ITEM}!"),    // 0x8df6399
    [131] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} can't\nescape now!"),    // 0x8df63ab
    [132] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} fell into\na Nightmare!"),    // 0x8df63c0
    [133] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} is locked\nin a Nightmare!"),    // 0x8df63da
    [134] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} cut its own HP and\nlaid a Curse on {B_DEF_NAME_WITH_PREFIX}!"),    // 0x8df63f7
    [135] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} is afflicted\nby the Curse!"),    // 0x8df6421
    [136] = COMPOUND_STRING("Spikes were scattered all around\nthe opponent's side!"),    // 0x8df643f
    [137] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX} is hurt\nby Spikes!"),    // 0x8df6475
    [138] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} identified\n{B_DEF_NAME_WITH_PREFIX}!"),    // 0x8df648b
    [139] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}'s Perish count\nfell to {B_BUFF1}!"),    // 0x8df649d
    [140] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} braced\nitself!"),    // 0x8df64bb
    [141] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} Endured\nthe hit!"),    // 0x8df64cd
    [142] = COMPOUND_STRING("Magnitude {B_BUFF1}!"),    // 0x8df64e1
    [143] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} cut its own HP\nand maximized Attack!"),    // 0x8df64ef
    [144] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} copied\n{B_DEF_NAME_WITH_PREFIX}'s stat changes!"),    // 0x8df6517
    [145] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} got free of\n{B_DEF_NAME_WITH_PREFIX}'s {B_BUFF1}!"),    // 0x8df6534
    [146] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} shed\nLeech Seed!"),    // 0x8df654c
    [147] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} blew away\nSpikes!"),    // 0x8df6560
    [148] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} fled from\nbattle!"),    // 0x8df6575
    [149] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} foresaw\nan attack!"),    // 0x8df658a
    [150] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} took the\n{B_BUFF1} attack!"),    // 0x8df65a0
    [151] = COMPOUND_STRING("{B_BUFF1}'s attack!"),    // 0x8df65d3
    [152] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} became the\ncenter of attention!"),    // 0x8df65e0
    [153] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} began\ncharging power!"),    // 0x8df6603
    [154] = COMPOUND_STRING("Nature Power turned into\n{B_CURRENT_MOVE}!"),    // 0x8df661c
    [155] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}'s status\nreturned to normal!"),    // 0x8df6639
    [156] = COMPOUND_STRING("{B_ACTIVE_NAME_WITH_PREFIX} has no\nmoves left!\p"),    // 0x8df6a24
    [157] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} was subjected\nto Torment!"),    // 0x8df6659
    [158] = COMPOUND_STRING("{B_ACTIVE_NAME_WITH_PREFIX} can't use the same\nmove in a row due to the Torment!\p"),    // 0x8df6a51
    [159] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} is tightening\nits focus!"),    // 0x8df6676
    [160] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} fell for\nthe Taunt!"),    // 0x8df6692
    [161] = COMPOUND_STRING("{B_ACTIVE_NAME_WITH_PREFIX} can't use\n{B_CURRENT_MOVE} after the Taunt!\p"),    // 0x8df6a8a
    [162] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} is ready to\nhelp {B_DEF_NAME_WITH_PREFIX}!"),    // 0x8df66a9
    [163] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} switched\nitems with its opponent!"),    // 0x8df66c1
    [164] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} copied\n{B_DEF_NAME_WITH_PREFIX}'s {B_DEF_ABILITY}!"),    // 0x8df6726
    [165] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} made a Wish!"),    // 0x8df6739
    [166] = COMPOUND_STRING("{B_BUFF1}'s Wish\ncame true!"),    // 0x8df6749
    [167] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} planted its roots!"),    // 0x8df675e
    [168] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} absorbed\nnutrients with its roots!"),    // 0x8df6774
    [169] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} anchored\nitself with its roots!"),    // 0x8df679a
    [170] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} made\n{B_DEF_NAME_WITH_PREFIX} drowsy!"),    // 0x8df67bd
    [171] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} knocked off\n{B_DEF_NAME_WITH_PREFIX}'s {B_LAST_ITEM}!"),    // 0x8df67d0
    [172] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} swapped abilities\nwith its opponent!"),    // 0x8df67e8
    [173] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} sealed the\nopponent's move(s)!"),    // 0x8df6810
    [174] = COMPOUND_STRING("{B_ACTIVE_NAME_WITH_PREFIX} can't use the\nsealed {B_CURRENT_MOVE}!\p"),    // 0x8df6aac
    [175] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} wants the\nopponent to bear a Grudge!"),    // 0x8df6832
    [176] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}'s {B_BUFF1} lost\nall its PP due to the Grudge!"),    // 0x8df685a
    [177] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} shrouded\nitself in {B_CURRENT_MOVE}!"),    // 0x8df6885
    [178] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}'s {B_CURRENT_MOVE}\nwas bounced back by Magic Coat!"),    // 0x8df689f
    [179] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} waits for a target\nto make a move!"),    // 0x8df68c7
    [180] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} Snatched\n{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s move!"),    // 0x8df68ed
    [181] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_SCR_ACTIVE_ABILITY}\nmade it rain!"),    // 0x8df6aee
    [182] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_SCR_ACTIVE_ABILITY}\nraised its Speed!"),    // 0x8df6b04
    [183] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} was protected\nby {B_DEF_ABILITY}!"),    // 0x8df6b1e
    [184] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}'s {B_DEF_ABILITY}\nprevents {B_ATK_NAME_WITH_PREFIX}\lfrom using {B_CURRENT_MOVE}!"),    // 0x8df6b36
    [185] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} restored HP\nusing its {B_DEF_ABILITY}!"),    // 0x8df6b59
    [186] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}'s {B_DEF_ABILITY}\nmade it the {B_BUFF1} type!"),    // 0x8df6b8f
    [187] = COMPOUND_STRING("{B_EFF_NAME_WITH_PREFIX}'s {B_DEF_ABILITY}\nprevents paralysis!"),    // 0x8df6bac
    [188] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}'s {B_DEF_ABILITY}\nprevents romance!"),    // 0x8df6bc8
    [189] = COMPOUND_STRING("{B_EFF_NAME_WITH_PREFIX}'s {B_DEF_ABILITY}\nprevents poisoning!"),    // 0x8df6be2
    [190] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}'s {B_DEF_ABILITY}\nprevents confusion!"),    // 0x8df6bfe
    [191] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}'s {B_DEF_ABILITY}\nraised its Fire power!"),    // 0x8df6c1a
    [192] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} anchors\nitself with {B_DEF_ABILITY}!"),    // 0x8df6c39
    [193] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_SCR_ACTIVE_ABILITY}\ncuts {B_DEF_NAME_WITH_PREFIX}'s Attack!"),    // 0x8df6c54
    [194] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_SCR_ACTIVE_ABILITY}\nprevents stat loss!"),    // 0x8df6c6e
    [195] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} was hurt by\n{B_DEF_NAME_WITH_PREFIX}'s {B_BUFF1}!"),    // 0x8df6c8a
    [196] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX} Traced\nit's foe's ability!"),    // 0x8df6ca2
    [197] = COMPOUND_STRING("sharply "),    // 0x8df6ef7
    [198] = COMPOUND_STRING("rose!"),    // 0x8df6f00
    [199] = COMPOUND_STRING("harshly "),    // 0x8df6f06
    [200] = COMPOUND_STRING("fell!"),    // 0x8df6f0f
    [201] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}'s {B_BUFF1}\n{B_BUFF2}"),    // 0x8df6f15
    [202] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}'s {B_BUFF1}\n{B_BUFF2}"),    // 0x8df6f20
    [203] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}'s {B_BUFF1}\n{B_BUFF2}"),    // 0x8df6f45
    [204] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}'s {B_BUFF1}\n{B_BUFF2}"),    // 0x8df6f50
    [205] = COMPOUND_STRING("A critical hit!"),    // 0x8df6f9a
    [206] = COMPOUND_STRING("It's a one-hit KO!"),    // 0x8df6faa
    [207] = COMPOUND_STRING("{PAUSE み1, {PAUSE そ2, and{PAUSE そ⋯ {PAUSE そ⋯ {PAUSE そ⋯ {PAUSE そ{PLAY_SE}— Poof!\p"),    // 0x8df6fbd
    [208] = COMPOUND_STRING("And⋯\p"),    // 0x8df6fe9
    [209] = COMPOUND_STRING("It's not very effective⋯"),    // 0x8df7011
    [210] = COMPOUND_STRING("It's super effective!"),    // 0x8df702a
    [211] = COMPOUND_STRING("{PLAY_SE}ち Got away safely!\p"),    // 0x8df7040
    [212] = COMPOUND_STRING("{PLAY_SE}ち Wild {B_BUFF1} fled!"),    // 0x8df7088
    [213] = COMPOUND_STRING("No! There's no running\nfrom a Trainer battle!\p"),    // 0x8df7169
    [214] = COMPOUND_STRING("Can't escape!\p"),    // 0x8df7198
    [215] = COMPOUND_STRING("Prof. Birch: Don't leave me like this!\p"),    // 0x8df71a7
    [216] = COMPOUND_STRING("But nothing happened!"),    // 0x8df71cf
    [217] = COMPOUND_STRING("But it failed!"),    // 0x8df71e5
    [218] = COMPOUND_STRING("It hurt itself in its\nconfusion!"),    // 0x8df71f4
    [219] = COMPOUND_STRING("The Mirror Move failed!"),    // 0x8df7215
    [220] = COMPOUND_STRING("It started to rain!"),    // 0x8df722d
    [221] = COMPOUND_STRING("A downpour started!"),    // 0x8df7241
    [222] = COMPOUND_STRING("Rain continues to fall."),    // 0x8df7255
    [223] = COMPOUND_STRING("The downpour continues."),    // 0x8df726d
    [224] = COMPOUND_STRING("The rain stopped."),    // 0x8df7285
    [225] = COMPOUND_STRING("A sandstorm brewed!"),    // 0x8df7297
    [226] = COMPOUND_STRING("The sandstorm rages."),    // 0x8df72ab
    [227] = COMPOUND_STRING("The sandstorm subsided."),    // 0x8df72c0
    [228] = COMPOUND_STRING("The sunlight got bright!"),    // 0x8df72d8
    [229] = COMPOUND_STRING("The sunlight is strong."),    // 0x8df72f1
    [230] = COMPOUND_STRING("The sunlight faded."),    // 0x8df7309
    [231] = COMPOUND_STRING("It started to hail!"),    // 0x8df731d
    [232] = COMPOUND_STRING("Hail continues to fall."),    // 0x8df7331
    [233] = COMPOUND_STRING("The hail stopped."),    // 0x8df7349
    [234] = COMPOUND_STRING("But it failed to Spit Up\na thing!"),    // 0x8df735b
    [235] = COMPOUND_STRING("But it failed to Swallow\na thing!"),    // 0x8df737d
    [236] = COMPOUND_STRING("The wind turned into a\nHeat Wave!"),    // 0x8df739f
    [237] = COMPOUND_STRING("All stat changes were\neliminated!"),    // 0x8df73c1
    [238] = COMPOUND_STRING("Coins scattered everywhere!"),    // 0x8df73e3
    [239] = COMPOUND_STRING("It was too weak to make\na Substitute!"),    // 0x8df73ff
    [240] = COMPOUND_STRING("The battlers shared\ntheir pain!"),    // 0x8df7425
    [241] = COMPOUND_STRING("A bell chimed!"),    // 0x8df7445
    [242] = COMPOUND_STRING("All affected Pokémon will\nfaint in three turns!"),    // 0x8df7454
    [243] = COMPOUND_STRING("There's no PP left for\nthis move!\p"),    // 0x8df7484
    [244] = COMPOUND_STRING("But there was no PP left\nfor the move!"),    // 0x8df74a7
    [245] = COMPOUND_STRING("{B_PLAYER_NAME} used\n{B_LAST_ITEM}!"),    // 0x8df79d0
    [246] = COMPOUND_STRING("Wally used\n{B_LAST_ITEM}!"),    // 0x8df79dc
    [247] = COMPOUND_STRING("The Trainer blocked the Ball!"),    // 0x8df79fa
    [248] = COMPOUND_STRING("Don't be a thief!"),    // 0x8df7a18
    [249] = COMPOUND_STRING("It dodged the thrown Ball!\nThis Pokémon can't be caught!"),    // 0x8df7a2a
    [250] = COMPOUND_STRING("You missed the Pokémon!"),    // 0x8df7a63
    [251] = COMPOUND_STRING("Oh, no!\nThe Pokémon broke free!"),    // 0x8df7a7b
    [252] = COMPOUND_STRING("Aww!\nIt appeared to be caught!"),    // 0x8df7a9b
    [253] = COMPOUND_STRING("Aargh!\nAlmost had it!"),    // 0x8df7aba
    [254] = COMPOUND_STRING("Shoot!\nIt was so close, too!"),    // 0x8df7ad0
    [255] = COMPOUND_STRING("Gotcha!\n{B_DEF_NAME} was caught!{WAIT_SE}{PLAY_BGM}づあ\p"),    // 0x8df7aed
    [256] = COMPOUND_STRING("Gotcha!\n{B_DEF_NAME} was caught!{WAIT_SE}{PLAY_BGM}づあ{PAUSE ァ"),    // 0x8df7b0b
    [257] = COMPOUND_STRING("Give a nickname to the\ncaptured {B_DEF_NAME}?"),    // 0x8df7b2b
    [258] = COMPOUND_STRING("{B_DEF_NAME} was sent to\n{B_PC_CREATOR_NAME} PC."),    // 0x8df7b4f
    [259] = COMPOUND_STRING("{B_DEF_NAME}'s data was\nadded to the Pokédex.\p"),    // 0x8df7b79
    [260] = COMPOUND_STRING("It is raining."),    // 0x8df7b9e
    [261] = COMPOUND_STRING("A sandstorm is raging."),    // 0x8df7bad
    [262] = COMPOUND_STRING("Can't escape!\p"),    // 0x8df58cd
    [263] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} ignored\norders while asleep!"),    // 0x8df74ce
    [264] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} ignored\norders!"),    // 0x8df74ee
    [265] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} began to nap!"),    // 0x8df7501
    [266] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} is\nloafing around!"),    // 0x8df7512
    [267] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} won't\nobey!"),    // 0x8df7528
    [268] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} turned away!"),    // 0x8df7537
    [269] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} pretended\nnot to notice!"),    // 0x8df7547
    [270] = COMPOUND_STRING("{B_TRAINER1_CLASS} {B_TRAINER1_NAME} is\nabout to use {B_BUFF2}.\pWill {B_PLAYER_NAME} change\nPokémon?"),    // 0x8df7563
    [271] = COMPOUND_STRING("{B_PLAYER_NAME} crept closer to\n{B_OPPONENT_MON1_NAME}!"),    // 0x8df75bc
    [272] = COMPOUND_STRING("{B_PLAYER_NAME} can't get any closer!"),    // 0x8df75d3
    [273] = COMPOUND_STRING("{B_OPPONENT_MON1_NAME} is watching\ncarefully!"),    // 0x8df75ec
    [274] = COMPOUND_STRING("{B_OPPONENT_MON1_NAME} is curious about\nthe {B_BUFF1}!"),    // 0x8df7606
    [275] = COMPOUND_STRING("{B_OPPONENT_MON1_NAME} is enthralled by\nthe {B_BUFF1}!"),    // 0x8df7622
    [276] = COMPOUND_STRING("{B_OPPONENT_MON1_NAME} completely ignored\nthe {B_BUFF1}!"),    // 0x8df763e
    [277] = COMPOUND_STRING("{B_PLAYER_NAME} threw a オカキクケ\nat the {B_OPPONENT_MON1_NAME}!"),    // 0x8df765c
    [278] = COMPOUND_STRING("{PLAY_SE}べ Announcer: You're out of\nSafari Balls! Game over!\p"),    // 0x8df7678
    [279] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_LAST_ITEM}\ncured paralysis!"),    // 0x8df7c04
    [280] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_LAST_ITEM}\ncured poison!"),    // 0x8df7c1d
    [281] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_LAST_ITEM}\nhealed its burn!"),    // 0x8df7c33
    [282] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_LAST_ITEM}\ndefrosted it!"),    // 0x8df7c4c
    [283] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_LAST_ITEM}\nwoke it from its sleep!"),    // 0x8df7c62
    [284] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_LAST_ITEM}\nsnapped it out of confusion!"),    // 0x8df7c82
    [285] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_LAST_ITEM}\ncured its {B_BUFF1} problem!"),    // 0x8df7ca7
    [286] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_LAST_ITEM}\nrestored health!"),    // 0x8df7ce4
    [287] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_LAST_ITEM}\nrestored {B_BUFF1}'s PP!"),    // 0x8df7cfd
    [288] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_LAST_ITEM}\nrestored its status!"),    // 0x8df7d17
    [289] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_LAST_ITEM}\nrestored its HP a little!"),    // 0x8df7d34
    [290] = COMPOUND_STRING("{B_LAST_ITEM} allows the\nuse of only {B_CURRENT_MOVE}!\p"),    // 0x8df7d56
    [291] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} hung on\nusing its {B_LAST_ITEM}!"),    // 0x8df7d75
    [292] = COMPOUND_STRING(""),    // 0x8df7d8e
    [293] = COMPOUND_STRING("{B_EFF_NAME_WITH_PREFIX}'s {B_EFF_ABILITY}\nprevents burns!"),    // 0x8df6cc0
    [294] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}'s {B_DEF_ABILITY}\nblocks {B_CURRENT_MOVE}!"),    // 0x8df6cd8
    [295] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}'s {B_ATK_ABILITY}\nrestored its HP a little!"),    // 0x8df6cfe
    [296] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_SCR_ACTIVE_ABILITY}\nwhipped up a sandstorm!"),    // 0x8df6d20
    [297] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_SCR_ACTIVE_ABILITY}\nprevents {B_BUFF1} loss!"),    // 0x8df6d64
    [298] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}'s {B_DEF_ABILITY}\ninfatuated {B_ATK_NAME_WITH_PREFIX}!"),    // 0x8df6d7e
    [299] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}'s {B_DEF_ABILITY}\nmade {B_CURRENT_MOVE} ineffective!"),    // 0x8df6d95
    [300] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_SCR_ACTIVE_ABILITY}\ncured its {B_BUFF1} problem!"),    // 0x8df6db2
    [301] = COMPOUND_STRING("It sucked up the\nLiquid Ooze!"),    // 0x8df6dd0
    [302] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX} transformed!"),    // 0x8df6dee
    [303] = COMPOUND_STRING("Electricity's power was\nweakened!"),    // 0x8df6904
    [304] = COMPOUND_STRING("Fire's power was\nweakened!"),    // 0x8df6926
    [305] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} hid\nunderwater!"),    // 0x8df5e81
    [306] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} sprang up!"),    // 0x8df5e94
    [307] = COMPOUND_STRING("HM moves can't be\nforgotten now.\p"),    // 0x8df6fef
    [308] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} found\none {B_LAST_ITEM}!"),    // 0x8df6941
    [309] = COMPOUND_STRING("Player defeated\n{B_TRAINER1_CLASS} {B_TRAINER1_NAME}!\p"),    // 0x8df75a4
    [310] = COMPOUND_STRING("A soothing aroma wafted\nthrough the area!"),    // 0x8df6952
    [311] = COMPOUND_STRING("Items can't be used now.{PAUSE ぞ"),    // 0x8df697c
    [312] = COMPOUND_STRING("For {B_SCR_ACTIVE_NAME_WITH_PREFIX},\n{B_LAST_ITEM} {B_BUFF1}"),    // 0x8df6998
    [313] = COMPOUND_STRING("Using {B_LAST_ITEM}, the {B_BUFF1}\nof {B_SCR_ACTIVE_NAME_WITH_PREFIX} {B_BUFF2}"),    // 0x8df6f2b
    [314] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX} used\n{B_LAST_ITEM} to get pumped!"),    // 0x8df69a6
    [315] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}'s {B_DEF_ABILITY}\nmade {B_CURRENT_MOVE} useless!"),    // 0x8df6b76
    [316] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} was trapped\nby Sand Tomb!"),    // 0x8df5ede
    [317] = COMPOUND_STRING(""),    // 0x8df55fc
    [318] = COMPOUND_STRING(" a boosted"),    // 0x8df55fd
    [319] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_SCR_ACTIVE_ABILITY}\nintensified the sun's rays!"),    // 0x8df6d40
    [320] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} makes Ground\nmoves miss with {B_DEF_ABILITY}!"),    // 0x8df5729
    [321] = COMPOUND_STRING("You throw a Ball now, right?\nI⋯ I'll do my best!"),    // 0x8df7d8f
    [322] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}'s {B_DEF_ABILITY}\ntook the attack!"),    // 0x8df6dfe
    [323] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} chose\n{B_CURRENT_MOVE} as its destiny!"),    // 0x8df65b7
    [324] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} lost its\nfocus and couldn't move!"),    // 0x8df69c0
    [325] = COMPOUND_STRING("Use next Pokémon?"),    // 0x8df56d3
    [326] = COMPOUND_STRING("{PLAY_SE}ち {B_ATK_NAME_WITH_PREFIX} fled\nusing its {B_LAST_ITEM}!\p"),    // 0x8df7056
    [327] = COMPOUND_STRING("{PLAY_SE}ち {B_ATK_NAME_WITH_PREFIX} fled\nusing {B_ATK_ABILITY}!\p"),    // 0x8df7071
    [328] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} was\ndragged out!\p"),    // 0x8df69e5
    [329] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}'s {B_DEF_ABILITY}\nprevented {B_SCR_ACTIVE_NAME_WITH_PREFIX}'s\l{B_BUFF1} from working!"),    // 0x8df6e34
    [330] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_LAST_ITEM}\nnormalized its status!"),    // 0x8df7cc5
    [331] = COMPOUND_STRING("{B_TRAINER1_CLASS} {B_TRAINER1_NAME}\nused {B_LAST_ITEM}!"),    // 0x8df79eb
    [332] = COMPOUND_STRING("The box is full!\nYou can't catch any more!\p"),    // 0x8df7bc4
    [333] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} avoided\nthe attack!"),    // 0x8df574d
    [334] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_SCR_ACTIVE_ABILITY}\nmade it ineffective!"),    // 0x8df6e5c
    [335] = COMPOUND_STRING("{B_EFF_NAME_WITH_PREFIX}'s {B_EFF_ABILITY}\nprevents flinching!"),    // 0x8df6e79
    [336] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} already\nhas a burn."),    // 0x8df5a2a
    [337] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}'s stats won't\ngo any lower!"),    // 0x8df6f7b
    [338] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_SCR_ACTIVE_ABILITY}\nblocks {B_CURRENT_MOVE}!"),    // 0x8df6ceb
    [339] = COMPOUND_STRING("{B_ATK_PREFIX1}'s {B_BUFF1}\nwore off!"),    // 0x8df6011
    [340] = COMPOUND_STRING("{B_ATK_PREFIX2}'s {B_CURRENT_MOVE}\nraised Defense a little!"),    // 0x8df5d46
    [341] = COMPOUND_STRING("{B_ATK_PREFIX2}'s {B_CURRENT_MOVE}\nraised Sp. Def a little!"),    // 0x8df5d0d
    [342] = COMPOUND_STRING("The wall shattered!"),    // 0x8df69fa
    [343] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}'s {B_ATK_ABILITY}\nprevents {B_DEF_NAME_WITH_PREFIX}'s\l{B_DEF_ABILITY} from working!"),    // 0x8df6e95
    [344] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_SCR_ACTIVE_ABILITY}\ncured its {B_BUFF1} problem!"),    // 0x8df6ebc
    [345] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} can't escape!"),    // 0x8df58dc
    [346] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} obtained\n{B_BUFF1}."),    // 0x8df66e6
    [347] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} obtained\n{B_BUFF2}."),    // 0x8df66f6
    [348] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} obtained\n{B_BUFF1}.\p{B_DEF_NAME_WITH_PREFIX} obtained\n{B_BUFF2}."),    // 0x8df6706
    [349] = COMPOUND_STRING("But it had no effect!"),    // 0x8df6a0e
    [350] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_SCR_ACTIVE_ABILITY}\nhad no effect on {B_EFF_NAME_WITH_PREFIX}!"),    // 0x8df6eda
    [351] = COMPOUND_STRING("{B_TRAINER1_CLASS} {B_TRAINER1_NAME} and\n{B_TRAINER2_CLASS} {B_TRAINER2_NAME}\lwere defeated!\p"),    // 0x8dfa9bf
    [352] = COMPOUND_STRING("{B_TRAINER2_LOSE_TEXT}"),    // 0x8dfa9df
    [353] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} appears incapable\nof using its power!"),    // 0x8dfa9e2
    [354] = COMPOUND_STRING("A glint appears in\n{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s eyes!"),    // 0x8dfaa0b
    [355] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX} is getting into\nposition!"),    // 0x8dfaa29
    [356] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX} began growling deeply!"),    // 0x8dfaa46
    [357] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX} is eager for more!"),    // 0x8dfaa60
    [358] = COMPOUND_STRING("{B_PLAYER_MON1_NAME} defeated the opponent\n{B_OPPONENT_MON1_NAME} in a Referee's decision!"),    // 0x8dfac73
    [359] = COMPOUND_STRING("{B_PLAYER_MON1_NAME} lost to the opponent\n{B_OPPONENT_MON1_NAME} in a Referee's decision!"),    // 0x8dfaca8
    [360] = COMPOUND_STRING("{B_PLAYER_MON1_NAME} tied the opponent\n{B_OPPONENT_MON1_NAME} in a Referee's decision!"),    // 0x8dfacdc
    [361] = COMPOUND_STRING("Would you like to forfeit the match\nand quit now?"),    // 0x8dfad58
    [362] = COMPOUND_STRING("{B_PLAYER_NAME} forfeited the match!"),    // 0x8dfad8a
    [363] = COMPOUND_STRING("{B_COPY_VAR_2} was transferred to\nSomeone's PC.\pIt was placed in \nBox “{B_COPY_VAR_1}.”"),    // 0x82ec3aa
    [364] = COMPOUND_STRING("{B_COPY_VAR_2} was transferred to\nLanette's PC.\pIt was placed in \nBox “{B_COPY_VAR_1}.”"),    // 0x82ec3ea
    [365] = COMPOUND_STRING("Box “{B_COPY_VAR_3}” on\nSomeone's PC was full.\p{B_COPY_VAR_2} was transferred to\nBox “{B_COPY_VAR_1}.”"),    // 0x82ec42a
    [366] = COMPOUND_STRING("Box “{B_COPY_VAR_3}” on\nLanette's PC was full.\p{B_COPY_VAR_2} was transferred to\nBox “{B_COPY_VAR_1}.”"),    // 0x82ec46d
    [367] = COMPOUND_STRING("{B_TRAINER1_WIN_TEXT}"),    // 0x8dfada2
    [368] = COMPOUND_STRING("{B_TRAINER2_WIN_TEXT}"),    // 0x8dfada5
    [369] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} ENDURED\nthe hit using {B_DEF_ABILITY}!"),    // 0x8df7dc0
    [370] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} became fully charged\ndue to its {B_LAST_ITEM}!"),    // 0x8df7ddd
    [371] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} was hurt\nby its {B_LAST_ITEM}!"),    // 0x8df7e04
    [372] = COMPOUND_STRING("{B_EFF_NAME_WITH_PREFIX} was badly \npoisoned by the {B_LAST_ITEM}!"),    // 0x8df7e1b
    [373] = COMPOUND_STRING("{B_EFF_NAME_WITH_PREFIX} was burned\nby the {B_LAST_ITEM}!"),    // 0x8df7e3d
    [374] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}'s {B_DEF_ABILITY} activates!"),    // 0x8df7e56
    [375] = COMPOUND_STRING("Gravity intensified!"),    // 0x8df7e69
    [376] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} was \nidentified!"),    // 0x8df7e7e
    [377] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} woke up!"),    // 0x8df7e92
    [378] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} stole and\nate {B_DEF_NAME_WITH_PREFIX}'s {B_LAST_ITEM}!"),    // 0x8df7e9e
    [379] = COMPOUND_STRING("The tailwind blew from\nbehind {B_ATK_TEAM2} team!"),    // 0x8df7eb8
    [380] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} went back\nto {B_ATK_TRAINER_CLASS} {B_ATK_TRAINER_NAME}"),    // 0x8df7edf
    [381] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} can't use\nitems anymore!"),    // 0x8df7ef5
    [382] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} flung its\n{B_LAST_ITEM}!"),    // 0x8df7f11
    [383] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} was prevented\nfrom healing!"),    // 0x8df7f22
    [384] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} switched its\nAttack and Defense!"),    // 0x8df7f41
    [385] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}'s ability\nwas suppressed!"),    // 0x8df7f65
    [386] = COMPOUND_STRING("The {B_CURRENT_MOVE} shielded {B_ATK_TEAM2}\nteam from critical hits!"),    // 0x8df7f82
    [387] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} switched all its\nchanges to its Attack and\pSp. Atk with the target!"),    // 0x8df7fae
    [388] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} switched all its\nchanges to its Defense and\pSp. Def with the target!"),    // 0x8df7ff5
    [389] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} acquired\n{B_DEF_ABILITY}!"),    // 0x8df803d
    [390] = COMPOUND_STRING("Poison Spikes were scattered all\naround the opposing team's feet!"),    // 0x8df804d
    [391] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} switched stat changes\nwith the target!"),    // 0x8df808f
    [392] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} surrounded itself\nwith a veil of water!"),    // 0x8df80b9
    [393] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} levitated on\nelectromagnetism!"),    // 0x8df80e4
    [394] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} twisted\nthe dimensions!"),    // 0x8df8106
    [395] = COMPOUND_STRING("Pointed stones float in the air\naround {B_DEF_TEAM2} team!"),    // 0x8df8121
    [396] = COMPOUND_STRING("It became cloaked in mystical\nmoonlight!"),    // 0x8df8151
    [397] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} became\ntrapped by swirling magma!"),    // 0x8df817a
    [398] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} vanished\ninstantly!"),    // 0x8df819f
    [399] = COMPOUND_STRING("{B_CURRENT_MOVE} protected\n{B_ATK_TEAM2} team!"),    // 0x8df81b6
    [400] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} shared its\nguard with the target!"),    // 0x8df81cc
    [401] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} shared its\npower with the target!"),    // 0x8df81f1
    [402] = COMPOUND_STRING("It created a bizarre area in which\nthe Defense and Sp.Def stats are swapped!"),    // 0x8df8216
    [403] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} became nimble!"),    // 0x8df8263
    [404] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} was hurled\ninto the air!"),    // 0x8df8275
    [405] = COMPOUND_STRING("It created a bizarre area in which\nPokémon's held items lose their effects!"),    // 0x8df8291
    [406] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} fell\nstraight down!"),    // 0x8df82dd
    [407] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} transformed\ninto the water type!"),    // 0x8df82f4
    [408] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} acquired\nSimple!"),    // 0x8df8318
    [409] = COMPOUND_STRING(""),    // 0x8df55fc
    [410] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}\ntook the kind offer!"),    // 0x8df832c
    [411] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}'s stat changes\nwere removed!"),    // 0x8df8344
    [412] = COMPOUND_STRING(""),    // 0x8df55fc
    [413] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} and\n{B_SCR_ACTIVE_NAME_WITH_PREFIX} switched places!"),    // 0x8df8364
    [414] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}'s HP was restored!"),    // 0x8df837f
    [415] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} took\n{B_DEF_NAME_WITH_PREFIX} into the sky!"),    // 0x8df8395
    [416] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} was freed\nfrom the Sky Drop!"),    // 0x8df83ae
    [417] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}'s move\nwas postponed!"),    // 0x8df83ce
    [418] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}'s type\nchanged to match the {B_DEF_NAME_WITH_PREFIX}'s!"),    // 0x8df83e7
    [419] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} received {B_LAST_ITEM}\nfrom {B_ATK_NAME_WITH_PREFIX}"),    // 0x8df840c
    [420] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} can\nuse items again!"),    // 0x8df8423
    [421] = COMPOUND_STRING("electromagnetism"),    // 0x8df843b
    [422] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}'s {B_BUFF1}\nwore off!"),    // 0x8df844c
    [423] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} was freed\nfrom the telekinesis!"),    // 0x8df8482
    [424] = COMPOUND_STRING("{B_ATK_TEAM1} team's tailwind\n petered out!"),    // 0x8df84a5
    [425] = COMPOUND_STRING("{B_ATK_TEAM1} team's Lucky Chant\n wore off!"),    // 0x8df84c6
    [426] = COMPOUND_STRING("The twisted dimensions returned to\nnormal!"),    // 0x8df84e7
    [427] = COMPOUND_STRING("Wonder Room wore off, and\nDefense and Sp. Def stats returned to normal!"),    // 0x8df8512
    [428] = COMPOUND_STRING("Magic Room wore off, and\nheld items' effects returned to normal!"),    // 0x8df855a
    [429] = COMPOUND_STRING("The effects of Mud Sport have faded."),    // 0x8df859b
    [430] = COMPOUND_STRING("The effects of Water Sport have faded."),    // 0x8df85c0
    [431] = COMPOUND_STRING("Gravity returned to normal!"),    // 0x8df85e7
    [432] = COMPOUND_STRING("Aqua Ring restored\n{B_ATK_NAME_WITH_PREFIX}'s HP!"),    // 0x8df8603
    [433] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}'s {B_DEF_ABILITY}\nwore off!"),    // 0x8df867c
    [434] = COMPOUND_STRING("The electricity disappeared\nfrom the battlefield."),    // 0x8df868e
    [435] = COMPOUND_STRING("The mist disappeared\nfrom the battlefield."),    // 0x8df86c0
    [436] = COMPOUND_STRING("The weirdness disappeared\nfrom the battlefield."),    // 0x8df86eb
    [437] = COMPOUND_STRING("The grass disappeared\nfrom the battlefield."),    // 0x8df871b
    [438] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}'s {B_DEF_ABILITY}\nraised its {B_BUFF1}!"),    // 0x8df861f
    [439] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}'s {B_DEF_ABILITY} maxed\nits attack!"),    // 0x8df8747
    [440] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}'s {B_ATK_ABILITY}\nraised its {B_BUFF1}!"),    // 0x8df864e
    [441] = COMPOUND_STRING("The poisoning healed {B_ATK_NAME_WITH_PREFIX}\na little bit!"),    // 0x8df8761
    [442] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} is tormented\nby {B_ATK_ABILITY}!"),    // 0x8df879f
    [443] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX} breaks the mold!"),    // 0x8df87b6
    [444] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX} is radiating \na bursting aura!"),    // 0x8df87ca
    [445] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX} is radiating\na blazing aura!"),    // 0x8df87ec
    [446] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX} can't get it going!"),    // 0x8df880c
    [447] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} finally got\nits act together!"),    // 0x8df8823
    [448] = COMPOUND_STRING("The {B_ATK_NAME_WITH_PREFIX}'s {B_ATK_ABILITY}\ntakes its toll!"),    // 0x8df8844
    [449] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} is hurt!"),    // 0x8df8860
    [450] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX} shuddered\nin anticipation!"),    // 0x8df886c
    [451] = COMPOUND_STRING("{B_SCR_ACTIVE_ABILITY} alerted {B_SCR_ACTIVE_NAME_WITH_PREFIX}\nto the {B_DEF_NAME_WITH_PREFIX}'s {B_BUFF1}!"),    // 0x8df888a
    [452] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}'s {B_ATK_ABILITY}\nhealed it a little bit!"),    // 0x8df88a8
    [453] = COMPOUND_STRING("It started to hail!"),    // 0x8df88c8
    [454] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} frisked {B_DEF_NAME_WITH_PREFIX} and\nfound its {B_LAST_ITEM}!"),    // 0x8df88dc
    [455] = COMPOUND_STRING("The opposing team is too nervous\nto eat Berries!"),    // 0x8df88fc
    [456] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} harvested\nits {B_LAST_ITEM}!"),    // 0x8df892d
    [457] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}'s {B_ATK_ABILITY} raised its Attack!"),    // 0x8df8942
    [458] = COMPOUND_STRING("The {B_DEF_NAME_WITH_PREFIX} bounced the\n{B_ATK_NAME_WITH_PREFIX} back!"),    // 0x8df895d
    [459] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}'s {B_ATK_ABILITY} transformed\nit into the {B_BUFF1} type!"),    // 0x8df8979
    [460] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} passed its {B_LAST_ITEM}\nto {B_SCR_ACTIVE_NAME_WITH_PREFIX} through {B_ATK_ABILITY}!"),    // 0x8df89a2
    [461] = COMPOUND_STRING("Pointed stones dug into\n{B_SCR_ACTIVE_NAME_WITH_PREFIX}!"),    // 0x8df89c5
    [462] = COMPOUND_STRING("The poison spikes disappeared\nfrom around the opposing team's feet!"),    // 0x8df89e1
    [463] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX} was poisoned!"),    // 0x8df8a25
    [464] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX} was\ncaught in a Sticky Web!"),    // 0x8df8a36
    [465] = COMPOUND_STRING("The healing wish came true\nfor {B_ATK_NAME_WITH_PREFIX}!"),    // 0x8df8a55
    [466] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} regained health!"),    // 0x8df8a78
    [467] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} became cloaked\nin mystical moonlight!"),    // 0x8df8a8c
    [468] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}'s {B_BUFF1} was disabled\nby {B_DEF_NAME_WITH_PREFIX}'s {B_DEF_ABILITY}!"),    // 0x8df8ab5
    [469] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} acquired {B_LAST_ABILITY}!"),    // 0x8df8ad6
    [470] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}'s {B_DEF_ABILITY}\nlowered its {B_BUFF1}!"),    // 0x8df8636
    [471] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}'s {B_BUFF1}\nwon't go higher!"),    // 0x8df8ae6
    [472] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}'s {B_CURRENT_MOVE} was\nbounced back by {B_DEF_NAME_WITH_PREFIX}'s\l{B_DEF_ABILITY}!"),    // 0x8df8aff
    [473] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} transformed into\n{B_DEF_NAME_WITH_PREFIX} using {B_LAST_ABILITY}!"),    // 0x8df8b24
    [474] = COMPOUND_STRING("The effects of the {B_LAST_ITEM} prevent status\nmoves from being used!\p"),    // 0x8df8d1e
    [475] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} can't use {B_CURRENT_MOVE}\nbecause of gravity!\p"),    // 0x8df8d5b
    [476] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} was\nprevented from healing!\p"),    // 0x8df8d80
    [477] = COMPOUND_STRING("This move effect is not done yet!\p"),    // 0x8df8b45
    [478] = COMPOUND_STRING("A sticky web spreads out on the\nground around {B_DEF_TEAM2} team!"),    // 0x8df8bb7
    [479] = COMPOUND_STRING("The opposing {B_ATK_NAME_WITH_PREFIX}'s move was postponed!"),    // 0x8df8bee
    [480] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} blew away\nTOXIC SPIKES!"),    // 0x8df8b68
    [481] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} blew away\nSTICKY WEB!"),    // 0x8df8b83
    [482] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} blew away\nSTEALTH ROCK!"),    // 0x8df8b9c
    [483] = COMPOUND_STRING("A deluge of ions showers\nthe battlefield!"),    // 0x8df8c14
    [484] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}'s stat changes were\nall reversed!"),    // 0x8df8c3e
    [485] = COMPOUND_STRING("Mist swirled about\nthe battlefield!"),    // 0x8df8c63
    [486] = COMPOUND_STRING("Grass grew to cover\nthe battlefield!"),    // 0x8df8c87
    [487] = COMPOUND_STRING("An electric current runs across\nthe battlefield!"),    // 0x8df8cac
    [488] = COMPOUND_STRING("The battlefield got weird!"),    // 0x8df8cdd
    [489] = COMPOUND_STRING("The {B_DEF_NAME_WITH_PREFIX}'s moves\nhave been electrified!"),    // 0x8df8cf8
    [490] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}'s {B_LAST_ITEM} is \nreacting to {B_ATK_TRAINER_NAME}'s Mega Ring!"),    // 0x8df8da0
    [491] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} has Mega\nEvolved!"),    // 0x8df8dea
    [492] = COMPOUND_STRING("drastically "),    // 0x8df8eac
    [493] = COMPOUND_STRING("severely "),    // 0x8df8eb9
    [494] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} has been afflicted\nwith an infestation by {B_ATK_NAME_WITH_PREFIX}!"),    // 0x8df8ec3
    [495] = COMPOUND_STRING("It had no effect\non {B_DEF_NAME_WITH_PREFIX}!"),    // 0x8df8ef4
    [496] = COMPOUND_STRING("The bursting flames\nhit {B_SCR_ACTIVE_NAME_WITH_PREFIX}!"),    // 0x8df8f0c
    [497] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} received {B_LAST_ITEM}\nfrom {B_ATK_NAME_WITH_PREFIX}!"),    // 0x8df8f28
    [498] = COMPOUND_STRING("{B_BUFF1} type was added to\n{B_DEF_NAME_WITH_PREFIX}!"),    // 0x8df8f40
    [499] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} fell for\nthe feint!"),    // 0x8df8f59
    [500] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} cannot\nuse {B_CURRENT_MOVE}!"),    // 0x8df8f70
    [501] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} is covered in powder!"),    // 0x8df8f82
    [502] = COMPOUND_STRING("When the flame touched the powder\non the Pokémon, it exploded!"),    // 0x8df8f9b
    [503] = COMPOUND_STRING("Belch cannot be used!\p"),    // 0x8df8fda
    [504] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} stole the target's\nboosted stats!"),    // 0x8df8ff1
    [505] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} can't stay airborne\nbecause of gravity!"),    // 0x8df9016
    [506] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} surrounds itself\nwith a protective mist!"),    // 0x8df9041
    [507] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} is healed\nby the grassy terrain!"),    // 0x8df906d
    [508] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} surrounds itself\nwith electrified terrain!"),    // 0x8df9091
    [509] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} surrounds itself\nwith psychic terrain!"),    // 0x8df90bf
    [510] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} is not affected\nthanks to its {B_LAST_ITEM}!"),    // 0x8df90e9
    [511] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} surrounded itself\nwith a veil of petals!"),    // 0x8df910e
    [512] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} surrounded itself\nwith a veil of sweetness!"),    // 0x8df913a
    [513] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} is protected\nby an aromatic veil!"),    // 0x8df9169
    [514] = COMPOUND_STRING("Congratulations, {B_PLAYER_NAME}!"),    // 0x8df918e
    [515] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} used the move\ninstructed by {B_BUFF1}!"),    // 0x8df91a3
    [516] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} can\nuse sound-based moves again!"),    // 0x8df845e
    [517] = COMPOUND_STRING("{B_ACTIVE_NAME_WITH_PREFIX} can't use\n{B_CURRENT_MOVE} due to Throat Chop!\p"),    // 0x8df6ac9
    [518] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}\nconcentrated intensely!"),    // 0x8df91c6
    [519] = COMPOUND_STRING("{B_LAST_ITEM} strengthened\n{B_ATK_NAME_WITH_PREFIX}'s power!"),    // 0x8df91e1
    [520] = COMPOUND_STRING("{B_LAST_ITEM} weakened the damage\nto {B_DEF_NAME_WITH_PREFIX}!"),    // 0x8df91fd
    [521] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} ate its {B_LAST_ITEM}!"),    // 0x8df921b
    [522] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX} floats in the air\nwith its {B_LAST_ITEM}!"),    // 0x8df922a
    [523] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}'s {B_LAST_ITEM} popped!"),    // 0x8df924c
    [524] = COMPOUND_STRING("{B_EFF_NAME_WITH_PREFIX}'s {B_LAST_ITEM}\nwas burnt up!"),    // 0x8df925c
    [525] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} stole and ate\n{B_EFF_NAME_WITH_PREFIX}'s {B_LAST_ITEM}!"),    // 0x8df9272
    [526] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}'s Illusion wore off!"),    // 0x8df928c
    [527] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} cured\n{B_DEF_NAME_WITH_PREFIX}'s problem!"),    // 0x8df92a4
    [528] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} burned itself out!"),    // 0x8df92bb
    [529] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}'s {B_LAST_ABILITY}\ncured {B_SCR_ACTIVE_NAME_WITH_PREFIX}'s problem!"),    // 0x8df92d1
    [530] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_SCR_ACTIVE_ABILITY}\nraised its {B_BUFF1}!"),    // 0x8df8665
    [531] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_SCR_ACTIVE_ABILITY}\nwas taken over!"),    // 0x8df92ed
    [532] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} is absorbing power!"),    // 0x8df9305
    [533] = COMPOUND_STRING("No one will be able to run away\nduring the next turn!"),    // 0x8df931c
    [534] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX} fell in love\nfrom the {B_LAST_ITEM}!"),    // 0x8df9352
    [535] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} became cloaked\nin a freezing light!"),    // 0x8df936f
    [536] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}'s {B_BUFF1}\nwas not lowered!"),    // 0x8df9396
    [537] = COMPOUND_STRING("{B_ATK_TRAINER_NAME}'s fervent wish\nhas reached {B_ATK_NAME_WITH_PREFIX}!"),    // 0x8df8dc8
    [538] = COMPOUND_STRING("The effects of weather\ndisappeared."),    // 0x8df93af
    [539] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX} is exerting its\npressure!"),    // 0x8df93d3
    [540] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX} is radiating\na dark aura!"),    // 0x8df93f0
    [541] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX} is radiating\na fairy aura!"),    // 0x8df940d
    [542] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX} reversed all\nother Pokémon's auras!"),    // 0x8df942b
    [543] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX} is drowsing!"),    // 0x8df9452
    [544] = COMPOUND_STRING("All screens on the field were\ncleansed!"),    // 0x8df9462
    [545] = COMPOUND_STRING(""),    // 0x0
    [546] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_SCR_ACTIVE_ABILITY}\nraised its {B_BUFF1}!"),    // 0x8df9499
    [547] = COMPOUND_STRING("A sandstorm kicked up!"),    // 0x8df94b0
    [548] = COMPOUND_STRING("Both Pokémon will perish\nin three turns!"),    // 0x8df94c7
    [549] = COMPOUND_STRING(""),    // 0x0
    [550] = COMPOUND_STRING(""),    // 0x0
    [551] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX} has two Abilities!"),    // 0x8df9526
    [552] = COMPOUND_STRING("All the stat changes were reset\n thanks to {B_DEF_NAME_WITH_PREFIX}'s {B_SCR_ACTIVE_ABILITY}!"),    // 0x8df953c
    [553] = COMPOUND_STRING(""),    // 0x0
    [554] = COMPOUND_STRING(""),    // 0x0
    [555] = COMPOUND_STRING(""),    // 0x0
    [556] = COMPOUND_STRING(""),    // 0x0
    [557] = COMPOUND_STRING(""),    // 0x0
    [558] = COMPOUND_STRING(""),    // 0x0
    [559] = COMPOUND_STRING(""),    // 0x0
    [560] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} started\nheating up its beak!"),    // 0x8df9633
    [561] = COMPOUND_STRING("{B_PLAYER_NAME} is out of\nusable Pokémon!\pPlayer lost against\n{B_TRAINER1_CLASS} {B_TRAINER1_NAME}!{PAUSE_UNTIL_PRESS}"),    // 0x8df57ec
    [562] = COMPOUND_STRING("{B_PLAYER_NAME} paid ¥{B_BUFF1} as the prize\nmoney⋯\p⋯ ⋯ ⋯ ⋯\p{B_PLAYER_NAME} whited out!{PAUSE_UNTIL_PRESS}"),    // 0x8df5826
    [563] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} transformed!"),    // 0x8df9653
    [564] = COMPOUND_STRING("{B_ATK_ABILITY} allows the\nuse of only {B_CURRENT_MOVE}!\p"),    // 0x8df9663
    [565] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} became fully charged\ndue to its bond with its trainer!\p"),    // 0x8df9682
    [566] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} became Ash-{B_BUFF1}!\p"),    // 0x8df96bd
    [567] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX} dropped\nits {B_LAST_ITEM}!{WAIT_SE}\p"),    // 0x8df96d0
    [568] = COMPOUND_STRING("The box is full."),    // 0x8e19e1e
    [569] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} healed a little bit!"),    // 0x8df8787
    [570] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} Inverted\nthe type Effectiveness!"),    // 0x8df8dff
    [571] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} Body\ncreated a Protective Veil!"),    // 0x8df8e23
    [572] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} created\na Protective Screen!"),    // 0x8df8e46
    [573] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_SCR_ACTIVE_ABILITY}\ncuts {B_DEF_NAME_WITH_PREFIX}'s Sp.Defense!"),    // 0x8df8e66
    [574] = COMPOUND_STRING("An strange force made everybody\nDrowsy!"),    // 0x8df8e84
    [575] = COMPOUND_STRING("Your whole party gained some\nExp. Points!\p"),    // 0x8df5573
    [576] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} did {B_BUFF1} Damage!"),    // 0x8df9991
    [577] = COMPOUND_STRING("{B_ACTIVE_NAME_WITH_PREFIX} became a {B_BUFF1}-type!"),    // 0x8df96e6
    [578] = COMPOUND_STRING("{B_ACTIVE_NAME_WITH_PREFIX} is ready to bite!"),    // 0x8df96fb
    [579] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}'s {B_CURRENT_MOVE}\nraised its {B_BUFF1}!"),    // 0x8df9710
    [580] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX}'s {B_SCR_ACTIVE_ABILITY}\nsurpressed everyone's ability!"),    // 0x8df9727
    [581] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} attacked a second\ntime thanks to {B_ATK_ABILITY}!"),    // 0x8df974e
    [582] = COMPOUND_STRING("The Legendary Pokemon {B_OPPONENT_MON1_NAME}\nis ready to test you."),    // 0x8df9776
    [583] = COMPOUND_STRING("All of {B_OPPONENT_MON1_NAME}'s\nstats raised drastically!"),    // 0x8df97a5
    [584] = COMPOUND_STRING("{B_OPPONENT_MON1_NAME} blocked the Ball!"),    // 0x8df97cb
    [585] = COMPOUND_STRING("Try Weakening {B_OPPONENT_MON1_NAME} a little more!"),    // 0x8df97e0
    [586] = COMPOUND_STRING("A mysterious force is surrounding the\nLegendary Pokemon {B_OPPONENT_MON1_NAME}!"),    // 0x8df9800
    [587] = COMPOUND_STRING("Neither Pokémon can run away!"),    // 0x8df983c
    [588] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} can no longer escape\nbecause it used {B_CURRENT_MOVE}!"),    // 0x8df985a
    [589] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} made a Wish!"),    // 0x8df9886
    [590] = COMPOUND_STRING(""),    // 0x0
    [591] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} picked everything\non its field side!"),    // 0x8df9896
    [592] = COMPOUND_STRING("{B_SCR_ACTIVE_NAME_WITH_PREFIX}'s {B_SCR_ACTIVE_ABILITY}\nraised its {B_BUFF1}!"),    // 0x8df94f0
    [593] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} swapped Abilities\nwith its target!"),    // 0x8df98be
    [594] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} was cured\nof its poisoning!"),    // 0x8df98e4
    [595] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} is protected\nby a pastel veil!"),    // 0x8df9903
    [596] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX}'s stat changes were\nall reset!"),    // 0x8df9925
    [597] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} was cursed!"),    // 0x8df9947
    [598] = COMPOUND_STRING("{B_DEF_NAME_WITH_PREFIX} became a {B_BUFF1}-type!"),    // 0x8df9956
    [599] = COMPOUND_STRING("{B_PLAYER_NAME} Trainer Skills went\nto ゃ {B_COPY_VAR_1}!\p"),    // 0x8df55bb
    [600] = COMPOUND_STRING("{B_PLAYER_NAME} got {B_COPY_VAR_1} Trainer Skills Exp.!\p"),    // 0x8df55dc
    [601] = COMPOUND_STRING("{B_PLAYER_NAME} got {B_BUFF1} Battle Point(s)\nfor winning!\p"),    // 0x8df57c4
    [602] = COMPOUND_STRING("{B_ATK_NAME_WITH_PREFIX} underwent a heroic\ntransformation!"),    // 0x8df996b

};